<script lang="ts">
    import type { WriteOperationError, TransferOperationType } from '$lib/file-explorer/types'
    import { getUserFriendlyMessage } from './transfer-error-messages'
    import { formatBytes } from '$lib/tauri-commands'
    import { tString } from '$lib/intl/messages.svelte'
    import { formatInteger } from '$lib/intl/number-format'

    interface Props {
        error: WriteOperationError
        operationType: TransferOperationType
    }

    const { error, operationType }: Props = $props()
    const friendly = $derived(getUserFriendlyMessage(error, operationType))

    /** The offending files to list, only for the too-large-for-filesystem error. */
    const oversizedFiles = $derived(error.type === 'files_too_large_for_filesystem' ? error.files : [])
    /** How many offenders aren't shown in the (capped) list. */
    const oversizedRemaining = $derived(
        error.type === 'files_too_large_for_filesystem' ? error.totalCount - error.files.length : 0,
    )
</script>

<div class="error-content">
    <!-- eslint-disable-next-line svelte/no-at-html-tags -- Markup is generated by getUserFriendlyMessage from typed error fields + tier classes; no user input. -->
    <p id="error-dialog-message" class="message selectable">{@html friendly.message}</p>
    {#if oversizedFiles.length > 0}
        <ul class="oversized-files selectable">
            {#each oversizedFiles as file (file.name)}
                <li><span class="file-name">{file.name}</span><span class="file-size">{formatBytes(file.size)}</span></li>
            {/each}
        </ul>
        {#if oversizedRemaining > 0}
            <p class="oversized-more">
                {tString('fileOperations.errorDialog.tooLargeAndMore', {
                    countText: formatInteger(oversizedRemaining),
                    count: oversizedRemaining,
                })}
            </p>
        {/if}
    {/if}
    <p class="suggestion">{friendly.suggestion}</p>
</div>

<style>
    .error-content {
        padding: 0 var(--spacing-xl) var(--spacing-lg);
    }

    .message {
        margin: 0 0 var(--spacing-sm);
        font-size: var(--font-size-md);
        color: var(--color-text-secondary);
        line-height: 1.5;
    }

    .suggestion {
        margin: 0;
        font-size: var(--font-size-sm);
        color: var(--color-text-tertiary);
        line-height: 1.5;
    }

    .oversized-files {
        margin: 0 0 var(--spacing-sm);
        padding: var(--spacing-sm) 0 0;
        list-style: none;
        max-height: 180px;
        overflow-y: auto;
    }

    .oversized-files li {
        display: flex;
        align-items: baseline;
        justify-content: space-between;
        gap: var(--spacing-md);
        padding: var(--spacing-xs) 0;
        font-size: var(--font-size-sm);
        border-bottom: 1px solid var(--color-border);
    }

    .oversized-files .file-name {
        color: var(--color-text-secondary);
        word-break: break-all;
    }

    .oversized-files .file-size {
        flex-shrink: 0;
        color: var(--color-text-tertiary);
        font-variant-numeric: tabular-nums;
    }

    .oversized-more {
        margin: 0 0 var(--spacing-sm);
        font-size: var(--font-size-sm);
        color: var(--color-text-tertiary);
    }

    .selectable {
        user-select: text;
        -webkit-user-select: text;
        cursor: text;
    }
</style>
