//! The strings Rust draws itself, in the language the user reads.
//!
//! Three surfaces can't get their text from the webview: the native menu bar
//! (built during `setup`, and redrawn by AppKit whenever it likes), the main
//! window's title bar, and the "Cmdr is already running" alert (which fires
//! before a webview exists at all). They still belong in the same message
//! catalogs as every other string, so translators work one pile; the build-time
//! generator lifts the subset Rust needs into [`NATIVE_STRINGS`] and this module
//! reads it.
//!
//! [`menu_t`] is a table lookup, deliberately: no ICU, no plurals, no
//! formatting. A menu label that seems to need a plural is a label to reshape,
//! ❌ not a reason to link an ICU engine into the app process. The one
//! concession is [`menu_t_with`], which replaces literal `{token}` spans the way
//! the `errors.*` pipeline does, because `Copy "photo.jpg"` and `Eject (Backup)`
//! can't be expressed without one and reshaping them would cost the user real
//! information.

use std::sync::RwLock;

use crate::ignore_poison::RwLockIgnorePoison as _;

// The table is generated from the message catalogs. The `#[path]` keeps the
// `.gen.rs` spelling the repo already uses to mark a generated artifact.
#[path = "native_strings.gen.rs"]
mod generated;

use generated::NATIVE_STRINGS;

/// One shipped locale's native strings.
///
/// Generated by `apps/desktop/scripts/gen-native-strings.ts`; the struct is
/// hand-written here so the field docs don't churn every time a label changes.
pub(crate) struct LocaleStrings {
    /// The catalog directory name, verbatim (`en`, `zh`). Compared
    /// case-insensitively.
    pub(crate) tag: &'static str,
    /// `(key, value)` pairs, sorted by key so [`lookup`] can binary-search.
    /// Empty for a locale whose native strings aren't translated yet, which is
    /// how a locale ships a translated app under an English menu bar.
    pub(crate) entries: &'static [(&'static str, &'static str)],
}

/// The catalog `en` always exists under. Every lookup falls back here, so a key
/// a translator hasn't reached yet renders in English rather than as a key.
const BASE_LOCALE: &str = "en";

/// The user's `appearance.language` setting, verbatim, or `None` for `'system'`.
///
/// The SETTING is stored rather than the resolved tag, so `'system'` keeps
/// meaning "the language the user reads NOW": [`refresh_active_locale`] re-reads
/// the OS every time it runs.
static LANGUAGE_PREFERENCE: RwLock<Option<String>> = RwLock::new(None);

/// The catalog [`menu_t`] currently reads, resolved from [`LANGUAGE_PREFERENCE`]
/// plus the OS. `None` until something asks, so a process that never draws a
/// menu never pays for the resolution.
///
/// Cached because a menu bar build asks ~150 times in a row and the macOS half
/// of the answer is a `NSUserDefaults` read each time.
static ACTIVE_LOCALE: RwLock<Option<String>> = RwLock::new(None);

/// Records the user's `appearance.language` choice and re-resolves.
///
/// `setting` is the raw setting value: a catalog tag the user pinned, or `None`
/// / `"system"` for "follow the OS".
///
/// Returns whether the active catalog MOVED, which is the caller's cue to
/// rebuild the menu bar. Switching from `'system'` to the language the OS
/// already reported changes nothing visible, and rebuilding for it would be a
/// visible flicker for no reason.
pub fn set_language_preference(setting: Option<String>) -> bool {
    *LANGUAGE_PREFERENCE.write_ignore_poison() = setting.filter(|value| value != "system");
    refresh_active_locale()
}

/// Re-resolves the active catalog from the stored preference plus the OS, and
/// reports whether it moved. Called at startup, on every OS locale change, and
/// whenever the language setting is written.
pub fn refresh_active_locale() -> bool {
    let resolved = resolve_active_locale();
    let mut active = ACTIVE_LOCALE.write_ignore_poison();
    if active.as_deref() == Some(resolved.as_str()) {
        return false;
    }
    *active = Some(resolved);
    true
}

/// The catalog the native surfaces are speaking right now, resolving it on first
/// use so nothing has to be initialized in the right order.
pub fn active_locale() -> String {
    if let Some(active) = ACTIVE_LOCALE.read_ignore_poison().clone() {
        return active;
    }
    refresh_active_locale();
    ACTIVE_LOCALE
        .read_ignore_poison()
        .clone()
        .unwrap_or_else(|| BASE_LOCALE.to_string())
}

/// One native string, in the active language.
///
/// Falls back to English when the active catalog hasn't got the key (a locale
/// mid-translation), and to the key itself when nothing has it. Never panics:
/// a native menu is built on the main thread inside AppKit callbacks that abort
/// the process on a panic, so a typo must cost a visibly wrong label, not a
/// crash. `every_menu_key_literal_exists_in_the_english_catalog` catches the typo at
/// test time instead.
pub fn menu_t(key: &str) -> String {
    let active = active_locale();
    lookup(&active, key)
        .or_else(|| lookup(BASE_LOCALE, key))
        .unwrap_or(key)
        .to_string()
}

/// One native string with literal `{token}` spans replaced, for the handful of
/// labels that name the thing they act on (`Copy "photo.jpg"`, `Eject (Backup)`).
///
/// Plain `str::replace`, matching the raw `errors.*` pipeline on the frontend:
/// the token is a marker in the text, not an ICU argument. A token the value
/// doesn't contain is silently ignored, which is the right behavior for a
/// translation that legitimately drops one.
pub fn menu_t_with(key: &str, args: &[(&str, &str)]) -> String {
    expand_tokens(&menu_t(key), args)
}

/// `value` with each `{token}` span replaced by its argument.
///
/// Split out from [`menu_t_with`] so the substitution rules can be tested
/// without touching the process-wide active locale, which every other test in
/// this module would then be racing against.
fn expand_tokens(value: &str, args: &[(&str, &str)]) -> String {
    let mut expanded = value.to_string();
    for (token, replacement) in args {
        expanded = expanded.replace(&format!("{{{token}}}"), replacement);
    }
    expanded
}

/// The value for `key` in `locale`'s table, or `None`.
fn lookup(locale: &str, key: &str) -> Option<&'static str> {
    let entries = NATIVE_STRINGS
        .iter()
        .find(|candidate| candidate.tag.eq_ignore_ascii_case(locale))?
        .entries;
    entries
        .binary_search_by_key(&key, |(candidate, _)| candidate)
        .ok()
        .map(|index| entries[index].1)
}

/// The catalog to read, from the user's pinned language if there is one and the
/// OS otherwise.
///
/// An explicit pick carries NO script guard (that guard exists to stop
/// auto-selection landing a Traditional-Chinese reader on the Simplified
/// catalog; a user who chose a language chose it). An unrecognized pick falls
/// back to English rather than to the OS, because "I picked something we don't
/// ship" is a broken setting, not a request to follow the system.
fn resolve_active_locale() -> String {
    let preference = LANGUAGE_PREFERENCE.read_ignore_poison().clone();
    match preference {
        Some(tag) => shipped_tag(&tag).unwrap_or(BASE_LOCALE).to_string(),
        None => super::os_ui_locale(),
    }
}

/// The table's own spelling of `tag`, or `None` if we ship no such catalog.
fn shipped_tag(tag: &str) -> Option<&'static str> {
    NATIVE_STRINGS
        .iter()
        .find(|candidate| candidate.tag.eq_ignore_ascii_case(tag))
        .map(|candidate| candidate.tag)
}

/// Serializes tests that depend on which catalog is active.
///
/// [`LANGUAGE_PREFERENCE`] and [`ACTIVE_LOCALE`] are process-wide, and cargo runs
/// a crate's tests as parallel threads in ONE process, so a test that pins a
/// language races every test that reads a translated string — including ones in
/// other modules, which is easy to miss. Any test on either side of that takes
/// this lock.
///
/// Returns the guard, and it must be held for the whole test: dropping it early
/// re-opens the window it exists to close.
#[cfg(test)]
pub(crate) fn lock_active_locale_for_tests() -> std::sync::MutexGuard<'static, ()> {
    use crate::IgnorePoison;
    static LOCK: std::sync::Mutex<()> = std::sync::Mutex::new(());
    LOCK.lock_ignore_poison()
}

#[cfg(test)]
mod tests {
    use super::*;

    /// The English table, which every other lookup falls back to.
    fn english() -> &'static [(&'static str, &'static str)] {
        NATIVE_STRINGS
            .iter()
            .find(|locale| locale.tag == BASE_LOCALE)
            .expect("the English catalog always ships")
            .entries
    }

    #[test]
    fn the_english_table_carries_the_menu_bar() {
        // A generator that silently emitted nothing would leave every label
        // falling back to its own key, which reads as a plausible-looking menu
        // of dotted paths rather than as a failure.
        assert!(english().len() > 100, "only {} native strings emitted", english().len());
        assert_eq!(lookup(BASE_LOCALE, "menu.bar.file"), Some("File"));
    }

    #[test]
    fn every_locale_table_is_sorted_so_the_binary_search_is_valid() {
        for locale in NATIVE_STRINGS {
            let mut sorted: Vec<&str> = locale.entries.iter().map(|(key, _)| *key).collect();
            sorted.sort_unstable();
            let actual: Vec<&str> = locale.entries.iter().map(|(key, _)| *key).collect();
            assert_eq!(actual, sorted, "{} is unsorted; regenerate the table", locale.tag);
        }
    }

    /// Every native label ends with U+2026, never three periods.
    ///
    /// macOS kerns `...` visibly worse next to system items, and it reads wrong
    /// beside the system's own menus. The labels live in the catalog now, so this
    /// is where the rule is enforced; the source-scanning twin in
    /// `menu_items::menu_labels_use_the_ellipsis_character` only covers whatever
    /// literals are still written in the menu files.
    #[test]
    fn menu_labels_end_with_the_ellipsis_character() {
        for locale in NATIVE_STRINGS {
            for (key, value) in locale.entries {
                assert!(
                    !value.ends_with("..."),
                    "{}/{key} ends with `...`; use the `…` character (U+2026): {value}",
                    locale.tag
                );
            }
        }
    }

    #[test]
    fn an_unknown_key_renders_as_itself_instead_of_panicking() {
        // The menu is built inside AppKit callbacks that abort on panic, so the
        // failure mode for a typo has to be a wrong label, never a crash. The key
        // goes through a binding on purpose: written inline it would be a literal
        // for `every_menu_key_literal_exists_in_the_english_catalog` to reject.
        let unknown = "menu.nope.notAThing";
        assert_eq!(menu_t(unknown), unknown);
    }

    #[test]
    fn a_locale_without_native_strings_falls_back_to_english() {
        // A tag with no table of its own (an unshipped language, or a locale
        // whose native strings aren't translated yet) lands on English rather
        // than on the raw key.
        assert_eq!(lookup("kl", "menu.bar.file"), None);
        assert_eq!(
            lookup("kl", "menu.bar.file").or_else(|| lookup(BASE_LOCALE, "menu.bar.file")),
            Some("File")
        );
    }

    #[test]
    fn every_shipped_locale_speaks_its_own_menu_bar() {
        // All nine translated locales carry the native strings, so no user reads
        // a Cmdr menu bar in English while the rest of the app is translated.
        for locale in NATIVE_STRINGS {
            assert!(
                !locale.entries.is_empty(),
                "{} has no native strings; run `pnpm intl:native-strings`",
                locale.tag
            );
            assert_ne!(
                lookup(locale.tag, "menu.bar.file"),
                None,
                "{} is missing menu.bar.file",
                locale.tag
            );
        }
    }

    #[test]
    fn an_unshipped_or_missing_pick_lands_on_english() {
        assert_eq!(shipped_tag("kl"), None);
        assert_eq!(shipped_tag("en-XA"), None, "the pseudolocale is not selectable");
        assert_eq!(shipped_tag("HU"), Some("hu"), "the tag is matched case-insensitively");
    }

    /// Setting the preference and reading back what it resolved to.
    ///
    /// One test rather than several, because the statics are process-wide: two
    /// tests writing them would race under the default parallel runner. It ends
    /// by restoring `'system'`, so nothing after it sees a pinned language.
    ///
    /// Writers aren't the only racers: every test that reads a translated string
    /// is one too, wherever it lives. [`lock_active_locale_for_tests`] is what
    /// both sides hold.
    #[test]
    fn the_preference_decides_the_catalog_and_says_when_it_moved() {
        let _guard = lock_active_locale_for_tests();

        // Start from a known state: earlier tests in this process may have
        // resolved the locale already.
        set_language_preference(Some("en".to_string()));
        assert_eq!(active_locale(), "en");

        // A pinned language the app ships.
        assert!(set_language_preference(Some("hu".to_string())), "en → hu is a move");
        assert_eq!(active_locale(), "hu");
        // Setting the same thing again is not a move, so nothing rebuilds.
        assert!(!set_language_preference(Some("hu".to_string())));

        // A language we don't ship is a broken setting, not a request to follow
        // the OS, so it lands on English.
        assert!(set_language_preference(Some("kl".to_string())));
        assert_eq!(active_locale(), "en");

        // `'system'` and `None` mean the same thing, and both hand the answer
        // back to the OS. Whether that MOVES anything depends on the machine
        // running the test, so only the resolved value is asserted.
        set_language_preference(Some("system".to_string()));
        let from_sentinel = active_locale();
        set_language_preference(None);
        assert_eq!(active_locale(), from_sentinel);
        assert!(
            shipped_tag(&from_sentinel).is_some(),
            "the OS answer has to be a catalog we ship, got {from_sentinel}"
        );
    }

    #[test]
    fn tokens_are_replaced_literally_with_no_icu_in_sight() {
        let named = lookup(BASE_LOCALE, "menu.context.copyNamed").expect("the key ships");
        assert_eq!(expand_tokens(named, &[("name", "holiday.jpg")]), "Copy \"holiday.jpg\"");

        // An uncontrolled value goes in verbatim: no escaping, no formatting, and
        // nothing that looks like a token in the VALUE gets a second pass.
        let eject = lookup(BASE_LOCALE, "menu.volume.eject").expect("the key ships");
        assert_eq!(
            expand_tokens(eject, &[("name", "Backup {Drive}")]),
            "Eject (Backup {Drive})"
        );
    }

    #[test]
    fn a_token_the_translation_dropped_costs_nothing() {
        // A translation that legitimately drops a token still renders; it just
        // renders without the value.
        assert_eq!(expand_tokens("File", &[("name", "x")]), "File");
    }

    /// Every `"menu.…"` literal anywhere in the crate names a key the English
    /// catalog has.
    ///
    /// `menu_t` deliberately never panics, so a typo would otherwise ship as a
    /// menu item labelled `menu.file.opne` and nothing would notice. Source
    /// parsing is the only guard available: building a real menu needs AppKit on
    /// the main thread.
    ///
    /// It scans for the literal rather than for `menu_t` CALL SITES on purpose:
    /// several keys are held in tables and passed as a variable (the tag colors
    /// in `menu_structure.rs`, the image-search items in `media_index_items.rs`,
    /// the pin/unpin pair), and those are exactly the ones a call-site parser
    /// would miss.
    #[test]
    fn every_menu_key_literal_exists_in_the_english_catalog() {
        let source_root = std::path::Path::new(env!("CARGO_MANIFEST_DIR")).join("src");
        let mut checked = 0usize;
        let mut missing: Vec<String> = Vec::new();

        for (path, source) in rust_sources(&source_root) {
            // The generated table IS the catalog, and this file's own doc
            // comments talk about keys that deliberately don't exist.
            if path.ends_with("native_strings.gen.rs") || path.ends_with("native_strings.rs") {
                continue;
            }
            for key in menu_key_literals(&source) {
                checked += 1;
                if lookup(BASE_LOCALE, &key).is_none() {
                    missing.push(format!("{}: {key}", path.display()));
                }
            }
        }

        assert!(
            checked > 100,
            "only {checked} menu-key literals parsed; the parser is broken, not the source"
        );
        assert!(
            missing.is_empty(),
            "these menu keys are absent from `messages/en/`:\n  {}",
            missing.join("\n  ")
        );
    }

    /// Every `.rs` file under the crate's `src/`, as `(path, contents)`.
    fn rust_sources(root: &std::path::Path) -> Vec<(std::path::PathBuf, String)> {
        let mut sources = Vec::new();
        let mut stack = vec![root.to_path_buf()];
        while let Some(dir) = stack.pop() {
            let Ok(entries) = std::fs::read_dir(&dir) else {
                continue;
            };
            for entry in entries.flatten() {
                let path = entry.path();
                if path.is_dir() {
                    stack.push(path);
                } else if path.extension().is_some_and(|ext| ext == "rs")
                    && let Ok(contents) = std::fs::read_to_string(&path)
                {
                    sources.push((path, contents));
                }
            }
        }
        sources
    }

    /// Every `"menu.…"` string literal in one source file.
    ///
    /// A literal starts at `"menu.` and runs to the next `"`. Prose in a doc
    /// comment can't match, because a key mentioned there is written in
    /// backticks rather than quotes.
    fn menu_key_literals(source: &str) -> Vec<String> {
        const OPEN: &str = "\"menu.";
        let mut keys = Vec::new();
        let mut rest = source;
        while let Some(at) = rest.find(OPEN) {
            let after = &rest[at + 1..]; // past the opening quote
            let Some(end) = after.find('"') else { break };
            keys.push(after[..end].to_string());
            rest = &after[end..];
        }
        keys
    }
}
