//! The message catalogs Cmdr ships, and the scripts their readers read.
//!
//! @generated by `apps/desktop/scripts/gen-shipped-locales.ts` from the catalog
//! directories under `apps/desktop/src/lib/intl/messages/`. DO NOT EDIT BY HAND:
//! run `pnpm intl:shipped-locales` from `apps/desktop/`, or just let the
//! `shipped-locales-fresh` check rewrite it on a local run.
//!
//! The `en-XA` pseudolocale is deliberately absent: auto-selection draws
//! only from this table, so leaving it out is what makes it unreachable.

use super::ShippedLocale;

/// Every catalog we ship, sorted by tag. See [`ShippedLocale`] for the fields.
//
// `rustfmt::skip`: layout here is the GENERATOR's output, and the freshness
// check diffs that output byte for byte. Letting rustfmt rewrap the table would
// make the two disagree forever, one reformatting what the other regenerates.
#[rustfmt::skip]
pub(crate) const SHIPPED_LOCALES: &[ShippedLocale] = &[
    ShippedLocale {
        tag: "de",
        script: "latn",
        default_script: "latn",
        region_scripts: &[],
    },
    ShippedLocale {
        tag: "en",
        script: "latn",
        default_script: "latn",
        region_scripts: &[],
    },
    ShippedLocale {
        tag: "en-AU",
        script: "latn",
        default_script: "latn",
        region_scripts: &[],
    },
    ShippedLocale {
        tag: "en-GB",
        script: "latn",
        default_script: "latn",
        region_scripts: &[],
    },
    ShippedLocale {
        tag: "es",
        script: "latn",
        default_script: "latn",
        region_scripts: &[],
    },
    ShippedLocale {
        tag: "fr",
        script: "latn",
        default_script: "latn",
        region_scripts: &[],
    },
    ShippedLocale {
        tag: "hu",
        script: "latn",
        default_script: "latn",
        region_scripts: &[],
    },
    ShippedLocale {
        tag: "nl",
        script: "latn",
        default_script: "latn",
        region_scripts: &[],
    },
    ShippedLocale {
        tag: "pt",
        script: "latn",
        default_script: "latn",
        region_scripts: &[],
    },
    ShippedLocale {
        tag: "sv",
        script: "latn",
        default_script: "latn",
        region_scripts: &[],
    },
    ShippedLocale {
        tag: "vi",
        script: "latn",
        default_script: "latn",
        region_scripts: &[],
    },
    ShippedLocale {
        tag: "zh",
        script: "hans",
        default_script: "hans",
        region_scripts: &[
            ("au", "hant"),
            ("bn", "hant"),
            ("gb", "hant"),
            ("gf", "hant"),
            ("hk", "hant"),
            ("id", "hant"),
            ("mo", "hant"),
            ("pa", "hant"),
            ("pf", "hant"),
            ("ph", "hant"),
            ("pz", "hant"),
            ("sr", "hant"),
            ("th", "hant"),
            ("tw", "hant"),
            ("uk", "hant"),
            ("us", "hant"),
            ("vd", "hant"),
            ("vn", "hant"),
            ("036", "hant"),
            ("096", "hant"),
            ("158", "hant"),
            ("254", "hant"),
            ("258", "hant"),
            ("344", "hant"),
            ("360", "hant"),
            ("446", "hant"),
            ("591", "hant"),
            ("608", "hant"),
            ("704", "hant"),
            ("740", "hant"),
            ("764", "hant"),
            ("826", "hant"),
            ("840", "hant"),
        ],
    },
    ShippedLocale {
        tag: "zh-Hant",
        script: "hant",
        default_script: "hans",
        region_scripts: &[
            ("au", "hant"),
            ("bn", "hant"),
            ("gb", "hant"),
            ("gf", "hant"),
            ("hk", "hant"),
            ("id", "hant"),
            ("mo", "hant"),
            ("pa", "hant"),
            ("pf", "hant"),
            ("ph", "hant"),
            ("pz", "hant"),
            ("sr", "hant"),
            ("th", "hant"),
            ("tw", "hant"),
            ("uk", "hant"),
            ("us", "hant"),
            ("vd", "hant"),
            ("vn", "hant"),
            ("036", "hant"),
            ("096", "hant"),
            ("158", "hant"),
            ("254", "hant"),
            ("258", "hant"),
            ("344", "hant"),
            ("360", "hant"),
            ("446", "hant"),
            ("591", "hant"),
            ("608", "hant"),
            ("704", "hant"),
            ("740", "hant"),
            ("764", "hant"),
            ("826", "hant"),
            ("840", "hant"),
        ],
    },
];
