/**
 * The write-operation vocabulary: operation types and phases, conflict policy,
 * start configuration, and the typed error union the error dialog words.
 * Re-exported from `$lib/file-explorer/types`, which stays the one import seam
 * for consumers.
 *
 * ❗ Imports only from the generated bindings (`SortColumn` / `SortOrder` there
 * are identical to the listing's own), so the barrel's re-export can't form an
 * import cycle back into `file-explorer/`.
 */

import type { ArchiveNameRefusal, SortColumn, SortOrder, TrashRefusalKind } from '$lib/ipc/bindings'

// ============================================================================
// Write operation types
// ============================================================================

/** Type of write operation. Mirrors the `WriteOperationType` enum in `bindings.ts`
 *  (the managed instant ops `rename` / `create_folder` / `create_file`, plus
 *  `archive_edit` — the zip mutation op — included). */
export type WriteOperationType =
  | 'copy'
  | 'move'
  | 'delete'
  | 'trash'
  | 'rename'
  | 'create_folder'
  | 'create_file'
  | 'archive_edit'
  | 'compress'

/** Transfer-style operations that share the progress UI. `archive_edit` (a zip
 *  temp+rename rewrite) reports progress like a transfer, so it rides this set.
 *  `compress` packs sources into a NEW zip with distinct backend identity and
 *  phase-specific source/output byte progress. */
export type TransferOperationType = 'copy' | 'move' | 'delete' | 'trash' | 'archive_edit' | 'compress'

/** Phase of a write operation. */
export type WriteOperationPhase =
  | 'scanning'
  | 'copying'
  | 'compressing'
  | 'finishing_compression'
  | 'transferring'
  | 'finishing_transfer'
  | 'deleting'
  | 'trashing'
  | 'rolling_back'
  | 'flushing'

/** How to handle conflicts when destination files already exist. */
export type ConflictResolution = 'stop' | 'skip' | 'overwrite' | 'rename' | 'overwrite_smaller' | 'overwrite_older'

/** Configuration for write operations. */
export interface WriteOperationConfig {
  /** Explicit destination leaf for a single-item copy or move. */
  destinationName?: string
  /** Progress update interval in milliseconds (default: 200) */
  progressIntervalMs?: number
  /** How to handle conflicts */
  conflictResolution?: ConflictResolution
  /** If true, only scan and detect conflicts without executing the operation */
  dryRun?: boolean
  /** Column to sort files by during copy (default: name) */
  sortColumn?: SortColumn
  /** Sort order for copy operation (default: ascending) */
  sortOrder?: SortOrder
  /** Preview scan ID to reuse cached scan results (from start_scan_preview) */
  previewId?: string | null
  /** Maximum number of conflicts to include in DryRunResult (default: 100) */
  maxConflictsToShow?: number
  /** Source filenames already known to conflict at the destination (from the pre-flight
   *  `scanVolumeForConflicts` call). When `conflictResolution` is `'skip'`, the backend
   *  bulk-skips these upfront so the progress bar reflects them immediately. Ignored
   *  for other resolution modes. */
  preKnownConflicts?: string[]
}

/** Result of starting a write operation. */
export interface WriteOperationStartResult {
  /** Unique operation ID for tracking and cancellation */
  operationId: string
  /** Type of operation started */
  operationType: WriteOperationType
}

// The write-operations event payload types (`WriteProgressEvent`,
// `WriteCompleteEvent`, `WriteErrorEvent`, `WriteSourceItemDoneEvent`,
// `WriteCancelledEvent`, `WriteSettledEvent`, `WriteConflictEvent`,
// `ScanProgressEvent`, `ConflictInfo`, `DryRunResult`) plus the scan-preview
// event payloads (`ScanPreviewProgressEvent` / `Complete` / `Error` /
// `Cancelled`) are now generated by tauri-specta. Import them from `$lib/tauri-commands`.

/** A file that exceeds the destination filesystem's per-file size limit. */
export interface OversizedFile {
  name: string
  size: number
}

/**
 * One file a stopped copy kept under a new name, because a folder that was
 * replacing it took its own.
 */
export interface RecoveredOriginal {
  /** The name the file had, which the folder now wears. */
  path: string
  /** Where its bytes are now. */
  keptAt: string
}

/**
 * Which half of a transfer refused the write, for `read_only_device`.
 *
 * A read-only DESTINATION means "put it somewhere else"; a read-only SOURCE
 * means "you can copy out of here, you just can't move out of here". The
 * backend says which, so the frontend never guesses it from a path.
 */
export type ReadOnlySide = 'source' | 'destination'

/**
 * Which half of a transfer refused on permission grounds, for `permission_denied`.
 *
 * Copying OUT of a folder that refuses reads and copying INTO one that refuses
 * writes are different fixes. `null` when the refusing site couldn't tell (a
 * rename, whose errno names neither parent), and the copy stays per-operation.
 */
export type PermissionSide = 'source' | 'destination'

/**
 * Which half of a transfer a volume was, for `device_disconnected`.
 *
 * The backend is handed both volumes when the transfer starts and says which one
 * left; ❌ the frontend never works it out from a path.
 */
export type TransferRole = 'source' | 'destination'

/**
 * The volume that left the mount table while a transfer was running.
 *
 * ❗ Every field was captured when the transfer STARTED. A volume that vanishes
 * is gone from the volume list by the time this is rendered, so there is nothing
 * left to look its name up in. `counterpartName` is the OTHER volume: where the
 * files that made it are, or where the ones that didn't still sit.
 */
export interface DisconnectedSide {
  role: TransferRole
  volumeId: string
  volumeName: string
  counterpartName: string
}

/**
 * Why a destination folder takes no writes, for `destination_not_writable`. Only
 * what the backend can tell apart: a backend that can't tell read-only from a
 * missing permission (a phone over ADB) says `unexplained`, and the frontend ❌
 * never guesses one.
 */
export type UnwritableReason = 'readOnlyFilesystem' | 'noPermission' | 'unexplained'

/**
 * What a permission refusal's errno says about whether administrator rights could
 * change the answer, for `permission_denied`.
 *
 * `folderPermissions` (`EACCES`) is a folder an administrator could write to;
 * `systemProtected` (`EPERM`) is the OS itself refusing, where administrator
 * rights change nothing, so the advice has to be different. `unclassified` is a
 * backend that words its own refusals (MTP, SMB) or an errno outside the two.
 * `objectStoreAccount` is an S3 account refusing: its keys, or a provider that
 * paused it (a usage cap, a billing hold), which one answer covers. The
 * backend derives it from the errno and the frontend ❌ never re-derives one.
 */
export type PermissionRefusal = 'folderPermissions' | 'systemProtected' | 'unclassified' | 'objectStoreAccount'

/** Error types for write operations (discriminated union). */
export type WriteOperationError =
  | { type: 'source_not_found'; path: string }
  | { type: 'destination_not_found'; path: string }
  // `path` is the FILE in the way, often a level above the folder the user picked.
  | { type: 'destination_not_a_folder'; path: string }
  | { type: 'source_not_connected'; path: string }
  | { type: 'destination_not_connected'; path: string }
  // The source's volume left the registry and nothing lists it any more (an unplugged phone).
  | { type: 'source_no_longer_connected'; path: string }
  | { type: 'destination_exists'; path: string }
  // `refusedFolder` is the folder the BACKEND proved refuses writes (it asked the
  // OS with `access(W_OK)` at the refusal); `null` means nothing could be proved,
  // and the copy falls back to its per-operation sentence. ❌ Never infer one from
  // `path`: a `rename(2)` needs both parents and the errno names neither.
  | {
      type: 'permission_denied'
      path: string
      message: string
      errno: number | null
      refusal: PermissionRefusal
      refusedFolder: string | null
      side: PermissionSide | null
    }
  // Measured before anything was written, so both sizes are real.
  | { type: 'insufficient_space'; required: number; available: number; volumeName: string | null }
  // The destination refused a write for lack of room or quota. Nothing was
  // measured, so there are no sizes to show.
  | { type: 'destination_full'; path: string }
  | { type: 'destination_inside_source'; source: string; destination: string }
  | { type: 'duplicate_source_names'; name: string; first: string; second: string }
  // A fresh zip would hold an entry the archive reader hides: a macOS `..\x`
  // reads as `../x`. Refused from the plan, before anything is compressed.
  | { type: 'archive_entry_name_refused'; entry: string; reason: ArchiveNameRefusal }
  // Two fresh-zip entries read back as one path (`a\b.txt` beside `a/b.txt`),
  // so one would hide the other. Refused from the plan.
  | { type: 'archive_entry_names_collide'; entry: string; other: string; archivePath: string }
  | { type: 'symlink_loop'; path: string }
  | { type: 'cancelled'; message: string }
  // `side` is null for a backend session that dropped (MTP, SMB), which has no
  // mount table behind it: the copy stays the volume-agnostic one.
  | { type: 'device_disconnected'; path: string; side: DisconnectedSide | null }
  // A move's closing flush couldn't prove the copied files were on disk, so every
  // original stayed where it was. `errno` is the OS's number, for the details block.
  | { type: 'move_not_confirmed'; path: string; errno: number | null; volumeName: string | null }
  | { type: 'read_only_device'; path: string; deviceName: string | null; side: ReadOnlySide }
  | { type: 'destination_not_writable'; path: string; reason: UnwritableReason }
  | { type: 'file_locked'; path: string }
  | { type: 'trash_not_supported'; path: string }
  | { type: 'connection_interrupted'; path: string }
  | { type: 'read_error'; path: string; message: string }
  | { type: 'write_error'; path: string; message: string }
  | { type: 'name_too_long'; path: string }
  | { type: 'invalid_name'; path: string; message: string }
  | { type: 'delete_pending'; path: string }
  | { type: 'source_in_cold_storage'; path: string }
  | { type: 'source_changed'; path: string }
  | {
      type: 'files_too_large_for_filesystem'
      /** The destination filesystem kind (snake_case tag, e.g. 'fat32'). */
      filesystem: string
      maxSize: number
      files: OversizedFile[]
      totalCount: number
    }
  // A cross-volume overwrite wrote the new file completely, then couldn't give it
  // the destination's name, and the file it was replacing is already gone.
  // `keptAt` is where the complete new data actually is (a ` (recovered)` name),
  // and it is the only copy in existence, so the message has to name it.
  | { type: 'new_data_kept_at'; path: string; keptAt: string; message: string }
  // The copy stopped partway, and a folder that was replacing one of the user's
  // files keeps its name. Each `recovered` entry is a file that moved to a
  // ` (recovered)` sibling rather than being discarded with the folder's aside;
  // the list is never empty. `cause` is what actually stopped the copy, so its
  // own advice survives.
  | { type: 'originals_kept_aside'; cause: WriteOperationError; recovered: RecoveredOriginal[] }
  // A cross-volume move whose copy LANDED completely and whose original couldn't be
  // removed, so the item is now in both places and nothing is lost. `path` is the
  // original that stayed (for a folder, the item inside it that refused), `landedAt`
  // the complete copy, and `cause` what refused the delete, so its own advice survives.
  | { type: 'source_not_removed'; path: string; landedAt: string; cause: WriteOperationError }
  // The OS wouldn't take items to the Trash. Separate from `io_error` because the
  // REASON decides what the dialog can offer: as an `io_error` it arrived as one
  // sentence macOS had written, leaving nothing to say but "try again", which a
  // permission refusal cannot act on. `message` is technical detail only.
  // `onlineOnly` overrides the reason: an evicted cloud file refuses as 513
  // (`notPermitted`) as readily as 3328, so the reason can't tell the two apart,
  // and the Full Disk Access offer must not attach to one. See
  // `write_operations/delete/cloud_trash.rs`.
  | { type: 'trash_refused'; itemCount: number; reason: TrashRefusalKind; message: string; onlineOnly?: boolean }
  | { type: 'io_error'; path: string; message: string }
  // Extracting from a password-protected archive. `wrongAttempt` is true when the
  // stored password was rejected. The FE should intercept this before the generic
  // error dialog and prompt for a password (then retry via `setArchivePassword`).
  | { type: 'archive_needs_password'; path: string; wrongAttempt: boolean }
