/**
 * Regenerates the analytics settings-defaults manifest the dashboard resolves against.
 *
 * Usage (from `apps/desktop/`):
 *   node scripts/gen-analytics-defaults.ts              # rewrite `next` from the working tree
 *   node scripts/gen-analytics-defaults.ts --promote X  # record release X's defaults (release.sh)
 *   node scripts/gen-analytics-defaults.ts --backfill   # rebuild `versions` from the release tags
 *
 * Why `next` is separate from `versions`. Between two releases, `package.json` still carries the
 * LAST shipped version, so keying the working tree's snapshot by it would rewrite the entry that
 * describes a release already running in the field, and every historical adoption number computed
 * from it would silently change. `next` holds the unreleased state instead, is never resolved
 * against, and `release.sh` promotes it under the real version number at the moment that state
 * becomes a release.
 *
 * What the generator reads and what it means: `gen-analytics-defaults-lib.ts`.
 */

import { existsSync, readFileSync, writeFileSync } from 'node:fs'
import { execFileSync } from 'node:child_process'
import { dirname, join } from 'node:path'
import { fileURLToPath } from 'node:url'
import {
  buildSnapshot,
  compareVersionsAsc,
  gitTree,
  promote,
  serializeManifest,
  snapshotsEqual,
  sortVersions,
  workingTree,
  type DefaultsManifest,
  type DefaultsSnapshot,
  type SnapshotResult,
} from './gen-analytics-defaults-lib.ts'

const ROOT_DIR = join(dirname(fileURLToPath(import.meta.url)), '..', '..', '..')
const MANIFEST_PATH = 'apps/analytics-dashboard/src/lib/server/settings-defaults.gen.json'

const MANIFEST_NOTE = [
  'Generated by apps/desktop/scripts/gen-analytics-defaults.ts. Do not edit by hand.',
  'Each `versions` entry is the COMPLETE set of settings that could appear in the heartbeat config shape',
  'for that release, at their default values. Entries are written only where a default actually changed,',
  'so resolution takes the newest entry at or below an install’s app version. A key missing from the',
  'resolved entry means the setting did not exist in that build, so that install has no opinion to count.',
  '`next` is the unreleased working-tree state; it is never resolved against.',
]

/** An empty manifest, for the first run and for `--backfill` starting from scratch. */
function emptyManifest(): DefaultsManifest {
  return { note: MANIFEST_NOTE, versions: {}, next: {} }
}

function readManifest(): DefaultsManifest {
  const path = join(ROOT_DIR, MANIFEST_PATH)
  if (!existsSync(path)) return emptyManifest()
  const parsed = JSON.parse(readFileSync(path, 'utf8')) as Partial<DefaultsManifest>
  return { note: MANIFEST_NOTE, versions: parsed.versions ?? {}, next: parsed.next ?? {} }
}

function writeManifest(manifest: DefaultsManifest): void {
  writeFileSync(join(ROOT_DIR, MANIFEST_PATH), serializeManifest({ ...manifest, note: MANIFEST_NOTE }))
}

/** Builds the working tree's snapshot, refusing to write a manifest with a known blind spot. */
function currentSnapshot(): DefaultsSnapshot {
  return requireResolved(buildSnapshot(workingTree(ROOT_DIR)), 'the working tree')
}

function requireResolved(result: SnapshotResult, label: string): DefaultsSnapshot {
  if (result.unresolved.length > 0) {
    const lines = result.unresolved.map((u) => `  - ${u.id} (${u.file}): default: ${u.expression}`)
    throw new Error(
      `Can't read ${result.unresolved.length} setting default(s) in ${label}:\n${lines.join('\n')}\n` +
        'These settings reach the analytics config shape, so leaving them out would make their adoption\n' +
        'unmeasurable. Either give the registry a literal default, or teach `evaluateDefault` the shape.',
    )
  }
  return result.snapshot
}

/** Release tags, oldest first, as bare versions (`v0.40.0` becomes `0.40.0`). */
function releaseVersions(): string[] {
  const out = execFileSync('git', ['tag', '--list', 'v*'], { cwd: ROOT_DIR, encoding: 'utf8' })
  return out
    .split('\n')
    .map((line) => line.trim())
    .filter((line) => /^v\d+\.\d+\.\d+$/.test(line))
    .map((line) => line.slice(1))
    .sort(compareVersionsAsc)
}

/**
 * Rebuilds `versions` from the release tags, keeping only the releases that changed something.
 *
 * Releases before the heartbeat started shipping a config shape are skipped: with no config on the
 * wire there's nothing to resolve, and an entry for them would only invite a reader to believe we
 * know something about those installs. A tag whose registry the parser can't read is skipped the
 * same way, and reported, so it stays visible rather than turning into a wrong number.
 */
function backfill(manifest: DefaultsManifest): DefaultsManifest {
  const versions: Record<string, DefaultsSnapshot> = {}
  const skipped: string[] = []
  let previous: DefaultsSnapshot | null = null

  for (const version of releaseVersions()) {
    const result = buildSnapshot(gitTree(ROOT_DIR, `v${version}`))
    if (!result.configShapeShipped) {
      skipped.push(`${version}: the heartbeat sent no config shape yet`)
      continue
    }
    let snapshot: DefaultsSnapshot
    try {
      snapshot = requireResolved(result, `v${version}`)
    } catch (e) {
      skipped.push(`${version}: ${e instanceof Error ? e.message.split('\n')[0] : String(e)}`)
      continue
    }
    if (previous !== null && snapshotsEqual(previous, snapshot)) continue
    versions[version] = snapshot
    previous = snapshot
  }

  console.log(`Backfilled ${String(Object.keys(versions).length)} version entries from the release tags.`)
  for (const line of skipped) console.log(`  skipped v${line}`)
  return { ...manifest, versions: sortVersions(versions) }
}

function main(): void {
  const args = process.argv.slice(2)
  const manifest = readManifest()

  if (args[0] === '--promote') {
    const version = args[1]
    if (version === undefined || !/^\d+\.\d+\.\d+$/.test(version)) {
      console.error('Usage: node scripts/gen-analytics-defaults.ts --promote <major.minor.patch>')
      process.exit(1)
    }
    writeManifest(promote(manifest, version, currentSnapshot()))
    console.log(`Recorded the settings defaults for v${version}.`)
    return
  }

  if (args[0] === '--backfill') {
    const backfilled = backfill(manifest)
    writeManifest({ ...backfilled, next: currentSnapshot() })
    return
  }

  const snapshot = currentSnapshot()
  writeManifest({ ...manifest, next: snapshot })
  console.log(`Wrote ${String(Object.keys(snapshot).length)} setting defaults to ${MANIFEST_PATH}.`)
}

main()
