import { Hono, type Context } from 'hono'
import type { Bindings } from './types'

const telemetry = new Hono<{ Bindings: Bindings }>()

// Crash report ingestion: writes to D1 for crash analysis
const maxCrashReportBytes = 64 * 1024
const crashReportRequiredFields = ['appVersion', 'osVersion', 'arch', 'signal'] as const
const maxBacktraceBytes = 5_000

interface CrashReport {
  appVersion: string
  osVersion: string
  arch: string
  signal: string
  /** Optional. `"release"` or `"debug"`; older clients don't set it (stored as NULL). */
  buildMode?: 'release' | 'debug'
  /** Optional. `CRASH-XXXXX` short ID generated by the desktop client. */
  shortId?: string
  /**
   * Optional. The `diag_<uuid>` diagnostics id. Groups sequential reports from one
   * install. Deliberately a separate id from the `anal_` analytics id so a voluntarily
   * attached email can never be joined to the analytics stream. Never an `anal_` value.
   */
  diagId?: string
  /** Optional. A beta tester's contact email, attached only when they tick the box at send time. */
  email?: string
  backtraceFrames?: string[]
  [key: string]: unknown
}

const crashShortIdPattern = /^CRASH-[23456789ABCDEFGHJKMNPQRSTUVWXYZ]{5}$/
// `diag_` + a v4 UUID (36 chars: 32 hex digits plus the 4 dashes). An `anal_`-prefixed value
// fails this check by construction, so the analytics id can never land in a crash column.
const diagIdPattern = /^diag_[0-9a-f-]{36}$/

/** Extract the first app-code frame from a backtrace (contains `cmdr` or `cmdr_lib`). */
function extractTopFunction(frames: string[] | undefined): string {
  if (!frames || !Array.isArray(frames)) return 'unknown'
  for (const frame of frames) {
    if (typeof frame === 'string' && (frame.includes('cmdr') || frame.includes('cmdr_lib'))) {
      return frame
    }
  }
  return 'unknown'
}

const emailShapePattern = /^[^\s@]+@[^\s@]+$/

/**
 * Validate an optional `string`-and-pattern field. `null` and `undefined` both mean "field
 * absent": some clients omit the keys, and Rust clients serialize `Option::None` as `null`
 * (specta's unified mode rejects `skip_serializing_if`), so both are accepted. A present
 * value must be a string matching `pattern`. Returns `null` if valid, else `errorMessage`.
 */
function validateOptionalPattern(value: unknown, pattern: RegExp, errorMessage: string): string | null {
  if (value === undefined || value === null) return null
  if (typeof value !== 'string' || !pattern.test(value)) return errorMessage
  return null
}

/**
 * Validate the runtime shape of a `POST /crash-report` body. Returns `null` if the
 * body is well-formed; otherwise returns the error message to surface as 400. We
 * type the input as `Record<string, unknown>` (not `CrashReport`) so the optional-
 * field checks aren't statically narrowed away; values arrive from `JSON.parse`
 * and can be any shape an attacker chooses.
 */
function validateCrashReportShape(report: Record<string, unknown>): string | null {
  for (const field of crashReportRequiredFields) {
    const value = report[field]
    if (typeof value !== 'string' || value.length === 0) {
      return `Missing required field: ${field}`
    }
  }
  const buildMode = report.buildMode
  if (buildMode !== undefined && buildMode !== null && buildMode !== 'release' && buildMode !== 'debug') {
    return 'Invalid buildMode'
  }
  // `diagId` is the `diag_<uuid>` diagnostics id; an `anal_`-prefixed value fails this shape
  // check, so the analytics id can never land in a crash column. `email` is loosely
  // shape-checked (stored verbatim for reply-only use, so we don't over-validate).
  return (
    validateOptionalPattern(report.shortId, crashShortIdPattern, 'Invalid shortId') ??
    validateOptionalPattern(report.diagId, diagIdPattern, 'Invalid diagId') ??
    validateOptionalPattern(report.email, emailShapePattern, 'Invalid email')
  )
}

telemetry.post('/crash-report', async (c) => {
  // Reject oversized payloads before parsing
  const contentLength = c.req.header('content-length')
  if (contentLength && parseInt(contentLength, 10) > maxCrashReportBytes) {
    return c.json({ error: 'Report too large' }, 400)
  }

  let rawBody: string
  try {
    rawBody = await c.req.text()
  } catch {
    return c.json({ error: 'Could not read request body' }, 400)
  }

  if (rawBody.length > maxCrashReportBytes) {
    return c.json({ error: 'Report too large' }, 400)
  }

  let rawReport: unknown
  try {
    rawReport = JSON.parse(rawBody)
  } catch {
    return c.json({ error: 'Invalid JSON' }, 400)
  }
  if (!rawReport || typeof rawReport !== 'object') {
    return c.json({ error: 'Invalid JSON' }, 400)
  }

  const validationError = validateCrashReportShape(rawReport as Record<string, unknown>)
  if (validationError) {
    return c.json({ error: validationError }, 400)
  }
  const report = rawReport as CrashReport

  // Hash IP with daily salt for deduplication (same pattern as update-check)
  const ip = c.req.header('cf-connecting-ip') ?? c.req.header('x-forwarded-for') ?? 'unknown'
  const dailySalt = new Date().toISOString().slice(0, 10) // YYYY-MM-DD
  const hashBuffer = await crypto.subtle.digest('SHA-256', new TextEncoder().encode(ip + dailySalt))
  const hashedIp = [...new Uint8Array(hashBuffer)].map((b) => b.toString(16).padStart(2, '0')).join('')

  const topFunction = extractTopFunction(report.backtraceFrames)
  const backtraceTruncated = JSON.stringify(report.backtraceFrames ?? []).slice(0, maxBacktraceBytes)

  const dbWrite = writeCrashReportToD1(c.env.TELEMETRY_DB, report, { hashedIp, topFunction, backtraceTruncated })

  try {
    c.executionCtx.waitUntil(dbWrite)
  } catch {
    // executionCtx unavailable (for example, in tests); await inline as fallback
    await dbWrite
  }

  return c.body(null, 204)
})

/** Server-derived fields the handler computes before persisting a crash report. */
interface CrashReportDerived {
  hashedIp: string
  topFunction: string
  backtraceTruncated: string
}

/**
 * Fire-and-forget D1 insert of a crash report. `build_mode`, `short_id`, `diag_id`, and `email`
 * are nullable; rows from older clients (or reports without an attached email) stay NULL.
 */
function writeCrashReportToD1(db: D1Database, report: CrashReport, derived: CrashReportDerived): Promise<unknown> {
  return db
    .prepare(
      `INSERT INTO crash_reports (hashed_ip, app_version, os_version, arch, signal, top_function, backtrace, build_mode, short_id, diag_id, email)
         VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)`,
    )
    .bind(
      derived.hashedIp,
      report.appVersion,
      report.osVersion,
      report.arch,
      report.signal,
      derived.topFunction,
      derived.backtraceTruncated,
      report.buildMode ?? null,
      report.shortId ?? null,
      report.diagId ?? null,
      report.email ?? null,
    )
    .run()
    .catch(() => {}) // Don't let D1 failure block the response
}

const versionPattern = /^\d+\.\d+\.\d+$/

// Heartbeat ingestion: one row per beat (launch + hourly) for true daily-active tracking.
// Identity is the random `anal_<uuid>` analytics id; no IP is stored (the id is the dedup key).
// The whole request body is capped, and the config blob is capped again on its own so a single
// fat config can't dominate the budget.
const maxHeartbeatBytes = 32 * 1024
const maxConfigJsonBytes = 16 * 1024
const heartbeatRequiredFields = ['analId', 'appVersion', 'osVersion', 'arch'] as const
// `anal_` + a v4 UUID (36 chars: 32 hex digits plus the 4 dashes).
const analIdPattern = /^anal_[0-9a-f-]{36}$/

interface Heartbeat {
  analId: string
  appVersion: string
  osVersion: string
  arch: string
  /** Optional. `"release"` or `"debug"`; older clients don't set it (stored as NULL). */
  buildMode?: 'release' | 'debug' | null
  /** Optional. The allowlisted config-shape snapshot, stored verbatim as `config_json`. */
  config?: Record<string, unknown> | null
}

/**
 * Validate the optional `buildMode` field. `null` and `undefined` both mean "absent": Rust
 * serializes `Option::None` as `null` (specta's unified mode rejects `skip_serializing_if`), so
 * tolerate both rather than rejecting upgrade-window beats.
 */
function validateBuildMode(buildMode: unknown): string | null {
  if (buildMode !== undefined && buildMode !== null && buildMode !== 'release' && buildMode !== 'debug') {
    return 'Invalid buildMode'
  }
  return null
}

/** Validate the optional `config` blob: must be a plain object, capped at `maxConfigJsonBytes`. */
function validateConfig(config: unknown): string | null {
  if (config === undefined || config === null) return null
  if (typeof config !== 'object' || Array.isArray(config)) return 'Invalid config'
  if (JSON.stringify(config).length > maxConfigJsonBytes) return 'Config too large'
  return null
}

/**
 * Validate the runtime shape of a `POST /heartbeat` body. Returns `null` if the body is
 * well-formed; otherwise the error message to surface as 400. Input is typed as
 * `Record<string, unknown>` (not `Heartbeat`) so the optional-field checks aren't statically
 * narrowed away: values arrive from `JSON.parse` and can be any shape a client sends.
 */
function validateHeartbeatShape(beat: Record<string, unknown>): string | null {
  for (const field of heartbeatRequiredFields) {
    const value = beat[field]
    if (typeof value !== 'string' || value.length === 0) {
      return `Missing required field: ${field}`
    }
  }
  if (!analIdPattern.test(beat.analId as string)) return 'Invalid analId'
  if (!versionPattern.test(beat.appVersion as string)) return 'Invalid appVersion'
  return validateBuildMode(beat.buildMode) ?? validateConfig(beat.config)
}

/** Read and parse the request body, enforcing the size cap. Returns the parsed object or an error. */
async function readHeartbeatBody(c: Context<{ Bindings: Bindings }>): Promise<Record<string, unknown> | Response> {
  const contentLength = c.req.header('content-length')
  if (contentLength && parseInt(contentLength, 10) > maxHeartbeatBytes) {
    return c.json({ error: 'Heartbeat too large' }, 400)
  }

  let rawBody: string
  try {
    rawBody = await c.req.text()
  } catch {
    return c.json({ error: 'Could not read request body' }, 400)
  }
  if (rawBody.length > maxHeartbeatBytes) {
    return c.json({ error: 'Heartbeat too large' }, 400)
  }

  let parsed: unknown
  try {
    parsed = JSON.parse(rawBody)
  } catch {
    return c.json({ error: 'Invalid JSON' }, 400)
  }
  if (!parsed || typeof parsed !== 'object') {
    return c.json({ error: 'Invalid JSON' }, 400)
  }
  return parsed as Record<string, unknown>
}

telemetry.post('/heartbeat', async (c) => {
  // Rate-limit by the caller IP before doing any work. The IP is used only for the limiter's
  // sliding window and is never stored. The binding is optional, so the gate is a no-op when absent.
  const ip = c.req.header('cf-connecting-ip') ?? c.req.header('x-forwarded-for') ?? 'unknown'
  if (c.env.HEARTBEAT_LIMITER) {
    const { success } = await c.env.HEARTBEAT_LIMITER.limit({ key: ip })
    if (!success) {
      return c.json({ error: 'Too many requests' }, 429)
    }
  }

  const parsed = await readHeartbeatBody(c)
  if (parsed instanceof Response) return parsed

  const validationError = validateHeartbeatShape(parsed)
  if (validationError) {
    return c.json({ error: validationError }, 400)
  }
  const beat = parsed as unknown as Heartbeat

  // The config blob is stored verbatim as a single JSON column (not per-field columns), so new
  // settings auto-absorb without a migration. We re-serialize to a canonical string for storage.
  const configJson = beat.config !== undefined && beat.config !== null ? JSON.stringify(beat.config) : null

  // Write to D1 (fire-and-forget). `build_mode` and `config_json` are nullable.
  const dbWrite = c.env.TELEMETRY_DB.prepare(
    `INSERT INTO heartbeat (anal_id, app_version, os_version, arch, build_mode, config_json)
         VALUES (?, ?, ?, ?, ?, ?)`,
  )
    .bind(beat.analId, beat.appVersion, beat.osVersion, beat.arch, beat.buildMode ?? null, configJson)
    .run()
    .catch(() => {}) // Don't let D1 failure block the response

  try {
    c.executionCtx.waitUntil(dbWrite)
  } catch {
    // executionCtx unavailable (for example, in tests); await inline as fallback
    await dbWrite
  }

  return c.body(null, 204)
})

// Update check proxy: tracks version and arch for active user counting, then redirects to latest.json
telemetry.get('/update-check/:version', async (c) => {
  const { version } = c.req.param()

  if (!versionPattern.test(version)) {
    return c.json({ error: 'Invalid version' }, 400)
  }

  const arch = c.req.query('arch') ?? 'unknown'

  // Hash IP with daily salt for deduplication without storing PII
  const ip = c.req.header('cf-connecting-ip') ?? c.req.header('x-forwarded-for') ?? 'unknown'
  const dailySalt = new Date().toISOString().slice(0, 10) // YYYY-MM-DD
  const hashBuffer = await crypto.subtle.digest('SHA-256', new TextEncoder().encode(ip + dailySalt))
  const hashedIp = [...new Uint8Array(hashBuffer)].map((b) => b.toString(16).padStart(2, '0')).join('')

  // Write to D1 (fire-and-forget). INSERT OR IGNORE deduplicates via UNIQUE constraint.
  const dbWrite = c.env.TELEMETRY_DB.prepare(
    `INSERT OR IGNORE INTO update_checks (date, hashed_ip, app_version, arch) VALUES (?, ?, ?, ?)`,
  )
    .bind(dailySalt, hashedIp, version, arch)
    .run()
    .catch(() => {})

  try {
    c.executionCtx.waitUntil(dbWrite)
  } catch {
    // executionCtx unavailable (for example, in tests); await inline as fallback
    await dbWrite
  }

  return c.redirect('https://getcmdr.com/latest.json', 302)
})

// Download redirect: tracks version, arch, and country, then redirects to GitHub Releases
const validArchitectures = new Set(['aarch64', 'x86_64', 'universal'])

telemetry.get('/download/:version/:arch', async (c) => {
  const { version, arch } = c.req.param()

  if (!versionPattern.test(version) || !validArchitectures.has(arch)) {
    return c.json({ error: 'Invalid version or architecture' }, 400)
  }

  const cf = c.req.raw.cf as { country?: string; continent?: string } | undefined
  const country = cf?.country ?? 'unknown'
  const continent = cf?.continent ?? 'unknown'

  // Write to D1 (fire-and-forget)
  const dbWrite = c.env.TELEMETRY_DB.prepare(
    `INSERT INTO downloads (app_version, arch, country, continent) VALUES (?, ?, ?, ?)`,
  )
    .bind(version, arch, country, continent)
    .run()
    .catch(() => {})

  try {
    c.executionCtx.waitUntil(dbWrite)
  } catch {
    // executionCtx unavailable (for example, in tests); await inline as fallback
    await dbWrite
  }

  // tauri-action names the Intel DMG `_x64.dmg`, not `_x86_64.dmg`. Map at the boundary;
  // we keep `x86_64` everywhere else (uname, Rust target triple, D1, telemetry, website).
  const fileArch = arch === 'x86_64' ? 'x64' : arch
  return c.redirect(`https://github.com/vdavid/cmdr/releases/download/v${version}/Cmdr_${version}_${fileArch}.dmg`, 302)
})

export { telemetry }
