fn main() {
    // When the playwright-e2e feature is active, generate a capability file that
    // grants the plugin's IPC permissions. This file is gitignored and only exists
    // during feature-enabled builds (the plugin's permission schemas aren't available
    // without the feature, so we can't put this in the static capabilities/).
    #[cfg(feature = "playwright-e2e")]
    {
        let cap_path = std::path::Path::new("capabilities").join("playwright.json");
        std::fs::write(
            &cap_path,
            r#"{
    "$schema": "../gen/schemas/desktop-schema.json",
    "identifier": "playwright",
    "description": "Playwright E2E testing plugin permissions (auto-generated by build.rs)",
    "windows": ["main"],
    "permissions": ["playwright:default"]
}
"#,
        )
        .expect("Failed to write playwright capability file");
    }

    // Clean up the generated capability file when building without the feature,
    // so it doesn't linger from a previous feature-enabled build.
    #[cfg(not(feature = "playwright-e2e"))]
    {
        let cap_path = std::path::Path::new("capabilities").join("playwright.json");
        if cap_path.exists() {
            let _ = std::fs::remove_file(&cap_path);
        }
    }

    tauri_build::build()
}
