fn main() {
    println!("cargo:rerun-if-changed=build.rs");
    println!("cargo:rerun-if-changed=resources/ai/.version");
    println!("cargo:rerun-if-changed=../scripts/download-llama-server.go");
    // `analytics::posthog` reads this via `option_env!`, which is baked at compile time. Without
    // this line, changing the env var between builds wouldn't trigger a recompile of that consumer.
    println!("cargo:rerun-if-env-changed=CMDR_POSTHOG_KEY");

    // Ensure resources/ai/ is populated before tauri_build::build() validates the
    // resource glob in tauri.conf.json. The Go script is idempotent (skips when
    // .version matches) and symlinks from the main clone in worktrees instead of
    // re-downloading. Without this, a fresh worktree's first `cargo check` fails
    // with an opaque glob error.
    ensure_llama_resources();

    // When the playwright-e2e feature is active, generate a capability file that
    // grants the plugin's IPC permissions. This file is gitignored and only exists
    // during feature-enabled builds (the plugin's permission schemas aren't available
    // without the feature, so we can't put this in the static capabilities/).
    #[cfg(feature = "playwright-e2e")]
    {
        // Write via temp + rename (the house atomic-write pattern). Besides atomicity, this
        // dodges a real failure: under OrbStack's file sharing, a host-side delete of this
        // exact file (which every non-feature macOS build does, below) leaves Docker
        // containers with a persistent ENOENT for the name — a direct O_CREAT open fails
        // while rename() onto the name succeeds (verified in-container via strace,
        // OrbStack on macOS 26, 2026-07-13). The Linux E2E build runs inside such a
        // container, so a plain `fs::write` here breaks it whenever a macOS build ran last.
        let cap_dir = std::path::Path::new("capabilities");
        let cap_path = cap_dir.join("playwright.json");
        let tmp_path = cap_dir.join(format!(".playwright.json.tmp-{}", std::process::id()));
        std::fs::write(
            &tmp_path,
            r#"{
    "$schema": "../gen/schemas/desktop-schema.json",
    "identifier": "playwright",
    "description": "Playwright E2E testing plugin permissions (auto-generated by build.rs)",
    "windows": ["main", "settings", "viewer-*", "shortcuts", "queue"],
    "permissions": [
        "playwright:default",
        "core:window:allow-title",
        "core:window:allow-set-title",
        "core:window:allow-set-size",
        "core:window:allow-set-min-size",
        "core:window:allow-set-focus"
    ]
}
"#,
        )
        .expect("Failed to write playwright capability temp file");
        std::fs::rename(&tmp_path, &cap_path).expect("Failed to move playwright capability file into place");
    }

    // Clean up the generated capability file when building without the feature,
    // so it doesn't linger from a previous feature-enabled build.
    #[cfg(not(feature = "playwright-e2e"))]
    {
        let cap_path = std::path::Path::new("capabilities").join("playwright.json");
        if cap_path.exists() {
            let _ = std::fs::remove_file(&cap_path);
        }
    }

    tauri_build::build()
}

fn ensure_llama_resources() {
    let status = std::process::Command::new("go")
        .args(["run", "scripts/download-llama-server.go"])
        .current_dir("..")
        .stdout(std::process::Stdio::inherit())
        .stderr(std::process::Stdio::inherit())
        .status();
    match status {
        Ok(s) if s.success() => {}
        Ok(s) => panic!(
            "download-llama-server.go failed with exit code {}. Run `cd apps/desktop && go run scripts/download-llama-server.go` to see the full output.",
            s.code().unwrap_or(-1),
        ),
        Err(e) => panic!(
            "Failed to invoke `go run scripts/download-llama-server.go`: {e}. Make sure `go` is on PATH (mise shims should handle this). This script downloads the llama-server binaries that Tauri bundles via `resources/ai/*`.",
        ),
    }
}
