// AUTO-GENERATED by scripts/gen-message-keys.js. Do not edit by hand.
// Run `pnpm intl:keys` (or the check pipeline) to refresh.

/** Every key present in `messages/en/*.json`. A wrong key is a typecheck error. */
export type MessageKey =
  | 'common.downloadsFdaHint'
  | 'transfer.delete'
  | 'transfer.fileOnly.allDone'
  | 'transfer.fileOnly.allSkippedMany'
  | 'transfer.fileOnly.allSkippedSingle'
  | 'transfer.fileOnly.mixedCopy'
  | 'transfer.fileOnly.mixedMove'
  | 'transfer.movedPhrase'
  | 'transfer.split.clean'
  | 'transfer.split.skipped'
  | 'transfer.trash'
