/**
 * ESLint configuration for api-server
 *
 * Strict TypeScript checking for the Cloudflare Worker.
 */
import js from '@eslint/js'
import prettierConfig from 'eslint-config-prettier'
import tseslint from 'typescript-eslint'
import globals from 'globals'
import noConfusableCallbackParams from '../../eslint-plugins/no-confusable-callback-params.js'

export default tseslint.config(
  {
    // `worker-configuration.d.ts` is generated by `wrangler types`: upstream runtime typings, not
    // ours to lint (it even ships eslint-disable directives that don't match our rule set).
    ignores: ['dist', 'node_modules', '.wrangler', 'keys', 'worker-configuration.d.ts'],
  },
  js.configs.recommended,
  prettierConfig,
  ...tseslint.configs.strictTypeChecked.map((config) => ({
    ...config,
    files: ['**/*.ts'],
  })),
  {
    files: ['**/*.ts'],
    plugins: {
      '@typescript-eslint': tseslint.plugin,
    },
    languageOptions: {
      ecmaVersion: 'latest',
      sourceType: 'module',
      globals: {
        ...globals.node,
        ...globals.es2021,
      },
      parserOptions: {
        projectService: true,
        tsconfigRootDir: import.meta.dirname,
      },
    },
    rules: {
      '@typescript-eslint/no-unused-vars': 'error',
      '@typescript-eslint/no-unsafe-assignment': 'error',
      '@typescript-eslint/no-unsafe-call': 'error',
      '@typescript-eslint/no-unsafe-member-access': 'error',
      '@typescript-eslint/no-unsafe-return': 'error',
      '@typescript-eslint/no-floating-promises': 'error',
      '@typescript-eslint/await-thenable': 'error',
      '@typescript-eslint/no-misused-promises': 'error',
      '@typescript-eslint/require-await': 'error',
      '@typescript-eslint/no-explicit-any': 'error',
      'no-console': 'off', // Allow console in server code
      complexity: ['error', { max: 15 }],
    },
  },
  {
    files: ['scripts/*.js', 'test/*.js'],
    languageOptions: {
      ecmaVersion: 'latest',
      sourceType: 'module',
      globals: {
        ...globals.node,
      },
    },
  },
  {
    // Test fixtures delete dynamic keys off mock objects, which runtime code shouldn't.
    files: ['src/**/*.test.ts'],
    rules: {
      '@typescript-eslint/no-dynamic-delete': 'off',
    },
  },
  {
    // Shared with the desktop app and analytics dashboard, which register the same rule
    // under the same name.
    files: ['src/**/*.ts'],
    plugins: { cmdr: { rules: { 'no-confusable-callback-params': noConfusableCallbackParams } } },
    rules: { 'cmdr/no-confusable-callback-params': 'error' },
  },
)
