package checks

import (
	"fmt"
	"os"
	"path/filepath"
)

// RunApiServerESLint runs ESLint on the API server.
func RunApiServerESLint(ctx *CheckContext) (CheckResult, error) {
	dir := filepath.Join(ctx.RootDir, "apps", "api-server")

	// Defense in depth: the type-aware rules need `worker-configuration.d.ts` (generated by
	// `wrangler types`) for every Worker global to resolve. Without it the test fixtures'
	// `as unknown as KVNamespace` assertions point at nothing, so the `no-unsafe-*` rules fire
	// across the suite and the local `--fix` pass reads those assertions as redundant and deletes
	// them. Refuse to run rather than report nonsense. The `api-server-worker-types` check (a
	// dependency) normally guarantees this exists.
	if _, statErr := os.Stat(filepath.Join(dir, "worker-configuration.d.ts")); os.IsNotExist(statErr) {
		return CheckResult{}, fmt.Errorf("api-server-eslint: worker-configuration.d.ts missing: run `pnpm --filter @cmdr/api-server types:gen` first (the api-server-worker-types check should have)")
	}

	return runESLintCheck(ctx, dir, []string{"*.ts", "*.js"}, true)
}
