package checks

import (
	"fmt"
	"os"
	"path/filepath"
)

// RunDashboardESLint runs ESLint on the analytics dashboard.
func RunDashboardESLint(ctx *CheckContext) (CheckResult, error) {
	dir := filepath.Join(ctx.RootDir, "apps", "analytics-dashboard")

	// Defense in depth: the type-aware config extends `.svelte-kit/tsconfig.json` (generated by
	// `svelte-kit sync`). Without it the project service can't build a TypeScript program, the
	// type-aware rules silently pass, and the local `--fix` would then delete their now-"unused"
	// eslint-disable directives. Refuse to run rather than corrupt source.
	if _, err := os.Stat(filepath.Join(dir, ".svelte-kit", "tsconfig.json")); os.IsNotExist(err) {
		return CheckResult{}, fmt.Errorf(".svelte-kit/tsconfig.json missing, the dashboard-svelte-kit-sync check should have generated it")
	}

	return runESLintCheck(ctx, dir, []string{"*.ts", "*.svelte"}, true)
}
