package checks

import (
	"fmt"
	"os"
	"os/exec"
	"path/filepath"
	"strings"
)

// The full (type-aware) ESLint config is split into TWO passes — one over
// `.svelte` files, one over everything else (TS + JS/config) — because linting
// `.svelte` and `.ts` together in a single `eslint .` invocation hits a
// typescript-eslint projectService cliff: interleaving svelte-eslint-parser
// virtual files with `.ts` files thrashes the TS program and runs ~25x slower
// (~616s combined vs ~15s + ~10s split). Both passes use the SAME config,
// rules, and tsconfig-built projectService, so coverage is identical — each
// resolves cross-file types fully (verified with planted cross-file
// `no-floating-promises` violations). Run as two parallel checks, this keeps
// type-aware linting in the default (non-slow) suite. See
// docs/notes/check-cpu-contention.md.
//
// Running all rules here (vs the non-type-aware `desktop-svelte-eslint`) also
// catches stale eslint-disable comments that the fast check can't detect (it
// suppresses reportUnusedDisableDirectives).

// RunDesktopESLintTypecheckSvelte runs the full type-aware ESLint config over
// the `.svelte` files only.
func RunDesktopESLintTypecheckSvelte(ctx *CheckContext) (CheckResult, error) {
	return runScopedESLintTypecheck(ctx, "Svelte", []string{"**/*.svelte"}, []string{"*.svelte"})
}

// RunDesktopESLintTypecheckTypescript runs the full type-aware ESLint config
// over everything EXCEPT `.svelte` (TS, plus the handful of JS/config files
// `eslint .` lints). Together with the Svelte pass this is an exact partition
// of `eslint .`'s file set, so nothing drops out of coverage.
func RunDesktopESLintTypecheckTypescript(ctx *CheckContext) (CheckResult, error) {
	return runScopedESLintTypecheck(ctx, "TypeScript", []string{".", "--ignore-pattern", "**/*.svelte"}, []string{"*.ts"})
}

// runScopedESLintTypecheck runs `eslint <scopeArgs>` with the full config
// (no ESLINT_NO_TYPECHECK), auto-fixing locally and check-only in CI.
// countExts feeds an approximate src file count for the success message.
func runScopedESLintTypecheck(ctx *CheckContext, label string, scopeArgs, countExts []string) (CheckResult, error) {
	dir := filepath.Join(ctx.RootDir, "apps", "desktop")

	// Defense in depth: the type-aware config extends `.svelte-kit/tsconfig.json`
	// (generated by `svelte-kit sync`). If it's missing, the projectService can't
	// build a TypeScript program, the type-aware rules silently pass, and the
	// `--fix` below would delete their now-"unused" eslint-disable directives
	// across the repo. Refuse to run rather than corrupt source. The
	// `desktop-svelte-kit-sync` check (a dependency) normally guarantees this exists.
	if _, statErr := os.Stat(filepath.Join(dir, ".svelte-kit", "tsconfig.json")); os.IsNotExist(statErr) {
		return CheckResult{}, fmt.Errorf("%s: .svelte-kit/tsconfig.json missing — run `pnpm exec svelte-kit sync` first (the desktop-svelte-kit-sync check should have)", label)
	}

	// Approximate file count for the success message (src only; informational).
	findCmd := exec.Command("find", buildFindArgs("src", countExts)...)
	findCmd.Dir = dir
	findOutput, _ := RunCommand(findCmd, true)
	fileCount := 0
	if strings.TrimSpace(findOutput) != "" {
		fileCount = len(strings.Split(strings.TrimSpace(findOutput), "\n"))
	}

	args := append([]string{"exec", "eslint"}, scopeArgs...)
	if !ctx.CI {
		args = append(args, "--fix")
	}
	cmd := exec.Command("pnpm", args...)
	cmd.Dir = dir

	output, err := RunCommand(cmd, true)
	if err != nil {
		if ctx.CI {
			return CheckResult{}, fmt.Errorf("type-aware lint errors (%s), run pnpm lint:fix locally\n%s", label, indentOutput(output))
		}
		return CheckResult{}, fmt.Errorf("eslint found unfixable errors (%s)\n%s", label, indentOutput(output))
	}

	if fileCount > 0 {
		result := Success(fmt.Sprintf("%d %s %s passed", fileCount, label, Pluralize(fileCount, "file", "files")))
		result.Total = fileCount
		return result, nil
	}
	return Success(fmt.Sprintf("%s files passed", label)), nil
}
