package checks

import (
	"fmt"
	"os"
	"path/filepath"
)

// RunWebsiteESLint runs ESLint on the website.
func RunWebsiteESLint(ctx *CheckContext) (CheckResult, error) {
	dir := filepath.Join(ctx.RootDir, "apps", "website")

	// Defense in depth: the type-aware rules need `.astro/types.d.ts` (generated by
	// `astro sync`) for `astro:content` to resolve. Without it `getCollection` is `any`
	// and the `no-unsafe-*` rules bury the real output in ~90 false positives. Refuse to
	// run rather than report nonsense. The `website-astro-sync` check (a dependency)
	// normally guarantees this exists.
	if _, statErr := os.Stat(filepath.Join(dir, ".astro", "types.d.ts")); os.IsNotExist(statErr) {
		return CheckResult{}, fmt.Errorf("website-eslint: .astro/types.d.ts missing: run `pnpm exec astro sync` first (the website-astro-sync check should have)")
	}

	return runESLintCheck(ctx, dir, []string{"*.ts", "*.astro", "*.js"}, true)
}
