/**
 * Advanced section settings (data only). Logic lives in `../settings-registry.ts`,
 * which concatenates this array into the full registry in section order.
 */

import type { SettingDefinitionSource } from '../types'

export const advancedSettings: SettingDefinitionSource[] = [
  {
    id: 'updates.attachEmailToReports',
    section: ['Advanced'],
    cardKey: 'settings.advanced.card.loggingAndDiagnostics',
    labelKey: 'settings.updates.attachEmailToReports.label',
    descriptionKey: 'settings.updates.attachEmailToReports.description',
    keywords: ['email', 'report', 'crash', 'error', 'contact', 'attach', 'reply', 'beta'],
    type: 'boolean',
    default: false,
    component: 'switch',
  },

  {
    id: 'advanced.logLlmCalls',
    section: ['Advanced'],
    cardKey: 'settings.advanced.card.loggingAndDiagnostics',
    labelKey: 'settings.advanced.logLlmCalls.label',
    descriptionKey: 'settings.advanced.logLlmCalls.description',
    keywords: ['llm', 'ai', 'log', 'debug', 'request', 'response', 'prompt', 'ask cmdr'],
    type: 'boolean',
    // Dev-on, prod-off: `import.meta.env.DEV` inlines to a build-time boolean, so a
    // developer's runs are inspectable out of the box while shipped builds stay off until
    // opt-in. The Rust default (`AtomicBool::new(cfg!(debug_assertions))`) matches, so the
    // two agree with or without the frontend push.
    default: import.meta.env.DEV,
    component: 'switch',
  },

  // ========================================================================
  // Advanced (auto-generated UI).
  //
  // `section: ['Advanced']` is the single home for these settings: they render
  // ONLY on the Advanced page (which auto-renders `getAdvancedSettings()`), never
  // mirrored onto a feature page. `cardKey` groups them into `SectionCard`s on
  // that page (one card per `cardKey`, see `AdvancedSection.svelte` +
  // `advanced-grouping.ts`). `getAdvancedSettings()` selects on `section[0]`, so
  // the page membership and the nav identity are the same `section`.
  // ========================================================================
  {
    id: 'advanced.prefetchBufferSize',
    section: ['Advanced'],
    cardKey: 'settings.advanced.card.performance',
    labelKey: 'settings.advanced.prefetchBufferSize.label',
    descriptionKey: 'settings.advanced.prefetchBufferSize.description',
    keywords: ['prefetch', 'buffer', 'scroll', 'performance'],
    type: 'number',
    default: 200,
    component: 'number-input',
    constraints: {
      min: 50,
      max: 1000,
      step: 50,
    },
  },
  {
    id: 'advanced.virtualizationBufferRows',
    section: ['Advanced'],
    cardKey: 'settings.advanced.card.performance',
    labelKey: 'settings.advanced.virtualizationBufferRows.label',
    descriptionKey: 'settings.advanced.virtualizationBufferRows.description',
    keywords: ['virtualization', 'buffer', 'row', 'render'],
    type: 'number',
    default: 20,
    component: 'number-input',
    constraints: {
      min: 5,
      max: 100,
      step: 5,
    },
  },
  {
    id: 'advanced.virtualizationBufferColumns',
    section: ['Advanced'],
    cardKey: 'settings.advanced.card.performance',
    labelKey: 'settings.advanced.virtualizationBufferColumns.label',
    descriptionKey: 'settings.advanced.virtualizationBufferColumns.description',
    keywords: ['virtualization', 'buffer', 'column', 'brief'],
    type: 'number',
    default: 2,
    component: 'number-input',
    constraints: {
      min: 1,
      max: 10,
      step: 1,
    },
  },
  {
    id: 'advanced.fileWatcherDebounce',
    section: ['Advanced'],
    cardKey: 'settings.advanced.card.fileWatching',
    labelKey: 'settings.advanced.fileWatcherDebounce.label',
    descriptionKey: 'settings.advanced.fileWatcherDebounce.description',
    keywords: ['watcher', 'debounce', 'refresh', 'delay'],
    type: 'duration',
    default: 200,
    component: 'duration',
    constraints: {
      unit: 'ms',
      minMs: 50,
      maxMs: 2000,
    },
  },
  {
    id: 'advanced.diskSpaceChangeThreshold',
    section: ['Advanced'],
    cardKey: 'settings.advanced.card.fileWatching',
    labelKey: 'settings.advanced.diskSpaceChangeThreshold.label',
    descriptionKey: 'settings.advanced.diskSpaceChangeThreshold.description',
    keywords: ['disk', 'space', 'threshold', 'poll', 'refresh', 'status', 'bar'],
    type: 'number',
    default: 1,
    component: 'number-input',
    constraints: {
      min: 0,
      max: 1000,
      step: 1,
    },
  },
  {
    id: 'fileViewer.suppressBinaryWarning',
    section: ['Advanced'],
    cardKey: 'settings.advanced.card.hintsAndWarnings',
    labelKey: 'settings.fileViewer.suppressBinaryWarning.label',
    descriptionKey: 'settings.fileViewer.suppressBinaryWarning.description',
    keywords: ['viewer', 'binary', 'image', 'pdf', 'raw', 'warning', 'banner', 'f3', 'quick', 'look'],
    type: 'boolean',
    default: false,
    component: 'switch',
  },
  {
    id: 'fileExplorer.suppressQuickLookHint',
    section: ['Advanced'],
    cardKey: 'settings.advanced.card.hintsAndWarnings',
    labelKey: 'settings.fileExplorer.suppressQuickLookHint.label',
    descriptionKey: 'settings.fileExplorer.suppressQuickLookHint.description',
    keywords: ['quick', 'look', 'preview', 'space', 'finder', 'hint', 'toast', 'reminder'],
    type: 'boolean',
    default: false,
    component: 'switch',
  },
  {
    id: 'fileExplorer.tabs.closedTabHistorySize',
    section: ['Advanced'],
    cardKey: 'settings.advanced.card.historyAndLimits',
    labelKey: 'settings.fileExplorer.tabs.closedTabHistorySize.label',
    descriptionKey: 'settings.fileExplorer.tabs.closedTabHistorySize.description',
    keywords: ['tab', 'closed', 'reopen', 'history', 'undo', 'pane'],
    type: 'number',
    default: 10,
    component: 'number-input',
    constraints: {
      min: 1,
      max: 50,
      step: 1,
    },
  },
  {
    id: 'advanced.dragThreshold',
    section: ['Advanced'],
    cardKey: 'settings.advanced.card.input',
    labelKey: 'settings.advanced.dragThreshold.label',
    descriptionKey: 'settings.advanced.dragThreshold.description',
    keywords: ['drag', 'threshold', 'pixel', 'distance'],
    type: 'number',
    default: 5,
    component: 'number-input',
    constraints: {
      min: 1,
      max: 50,
      step: 1,
    },
  },
  {
    id: 'fileExplorer.typeToJump.resetDelay',
    section: ['Advanced'],
    cardKey: 'settings.advanced.card.input',
    labelKey: 'settings.fileExplorer.typeToJump.resetDelay.label',
    descriptionKey: 'settings.fileExplorer.typeToJump.resetDelay.description',
    keywords: ['type', 'jump', 'reset', 'delay', 'fuzzy', 'search', 'navigation', 'keystroke', 'buffer'],
    type: 'number',
    default: 1000,
    component: 'number-input',
    constraints: {
      min: 300,
      max: 3000,
      step: 100,
    },
  },
  {
    id: 'fileOperations.maxConflictsToShow',
    section: ['Advanced'],
    cardKey: 'settings.advanced.card.fileOperations',
    labelKey: 'settings.fileOperations.maxConflictsToShow.label',
    descriptionKey: 'settings.fileOperations.maxConflictsToShow.description',
    keywords: ['conflict', 'max', 'limit', 'preview', 'operation'],
    type: 'number',
    default: 100,
    component: 'select',
    constraints: {
      // Numeric option labels are plain numerals, not translatable copy.
      options: [
        { value: 1, label: '1' },
        { value: 2, label: '2' },
        { value: 3, label: '3' },
        { value: 5, label: '5' },
        { value: 10, label: '10' },
        { value: 50, label: '50' },
        { value: 100, label: '100' },
        { value: 200, label: '200' },
        { value: 500, label: '500' },
      ],
      allowCustom: true,
      customMin: 1,
      customMax: 1000,
    },
  },
  {
    id: 'fileOperations.progressUpdateInterval',
    section: ['Advanced'],
    cardKey: 'settings.advanced.card.fileOperations',
    labelKey: 'settings.fileOperations.progressUpdateInterval.label',
    descriptionKey: 'settings.fileOperations.progressUpdateInterval.description',
    keywords: ['progress', 'update', 'interval', 'refresh', 'cpu', 'performance'],
    type: 'number',
    default: 500,
    component: 'slider',
    constraints: {
      min: 50,
      max: 5000,
      step: 50,
      sliderStops: [100, 250, 500, 1000, 2000],
    },
  },
  {
    id: 'advanced.maxLogStorageMb',
    section: ['Advanced'],
    cardKey: 'settings.advanced.card.loggingAndDiagnostics',
    labelKey: 'settings.advanced.maxLogStorageMb.label',
    descriptionKey: 'settings.advanced.maxLogStorageMb.description',
    keywords: ['log', 'storage', 'disk', 'mb', 'cap', 'rotation', 'error', 'report', 'privacy'],
    type: 'number',
    default: 200,
    component: 'number-input',
    constraints: {
      min: 0,
      max: 5000,
      step: 50,
    },
  },
  {
    id: 'advanced.mountTimeout',
    section: ['Advanced'],
    cardKey: 'settings.advanced.card.networkAndMounts',
    labelKey: 'settings.advanced.mountTimeout.label',
    descriptionKey: 'settings.advanced.mountTimeout.description',
    keywords: ['mount', 'timeout', 'network', 'share'],
    type: 'duration',
    default: 20000,
    component: 'duration',
    constraints: {
      unit: 's',
      minMs: 5000,
      maxMs: 120000,
    },
  },
  {
    id: 'advanced.filterSafeSaveArtifacts',
    section: ['Advanced'],
    cardKey: 'settings.advanced.card.networkAndMounts',
    labelKey: 'settings.advanced.filterSafeSaveArtifacts.label',
    descriptionKey: 'settings.advanced.filterSafeSaveArtifacts.description',
    keywords: ['smb', 'safe-save', 'artifact', 'temp', 'sb', 'filter', 'watcher'],
    type: 'boolean',
    default: true,
    component: 'switch',
  },
  {
    id: 'advanced.serviceResolveTimeout',
    section: ['Advanced'],
    cardKey: 'settings.advanced.card.networkAndMounts',
    labelKey: 'settings.advanced.serviceResolveTimeout.label',
    descriptionKey: 'settings.advanced.serviceResolveTimeout.description',
    keywords: ['bonjour', 'resolve', 'timeout', 'mdns'],
    type: 'duration',
    default: 5000,
    component: 'duration',
    constraints: {
      unit: 's',
      minMs: 1000,
      maxMs: 30000,
    },
  },
  {
    id: 'network.smbConcurrency',
    section: ['Advanced'],
    cardKey: 'settings.advanced.card.networkAndMounts',
    labelKey: 'settings.network.smbConcurrency.label',
    descriptionKey: 'settings.network.smbConcurrency.description',
    keywords: ['smb', 'concurrency', 'parallel', 'copy', 'batch', 'performance', 'transfer', 'speed'],
    type: 'number',
    default: 10,
    component: 'number-input',
    constraints: {
      min: 1,
      max: 32,
      step: 1,
    },
  },
  {
    id: 'search.recentSearches.maxCount',
    section: ['Advanced'],
    cardKey: 'settings.advanced.card.historyAndLimits',
    labelKey: 'settings.search.recentSearches.maxCount.label',
    descriptionKey: 'settings.search.recentSearches.maxCount.description',
    keywords: ['search', 'recent', 'history', 'cap', 'limit', 'max', 'count'],
    type: 'number',
    default: 1000,
    component: 'number-input',
    constraints: {
      min: 0,
      max: 10000,
      step: 1,
    },
  },
  {
    id: 'selection.recentSelections.maxCount',
    section: ['Advanced'],
    cardKey: 'settings.advanced.card.historyAndLimits',
    labelKey: 'settings.selection.recentSelections.maxCount.label',
    descriptionKey: 'settings.selection.recentSelections.maxCount.description',
    keywords: ['selection', 'select', 'recent', 'history', 'cap', 'limit', 'max', 'count'],
    type: 'number',
    default: 1000,
    component: 'number-input',
    constraints: {
      min: 0,
      max: 10000,
      step: 1,
    },
  },
  {
    id: 'onboarding.upgradeNudgeShown',
    section: ['Advanced'],
    labelKey: 'settings.onboarding.upgradeNudgeShown.label',
    descriptionKey: 'settings.onboarding.upgradeNudgeShown.description',
    keywords: [],
    type: 'boolean',
    default: false,
    component: 'switch',
    hidden: true,
  },
  {
    id: 'advanced.updateCheckInterval',
    section: ['Advanced'],
    cardKey: 'settings.advanced.card.updates',
    labelKey: 'settings.advanced.updateCheckInterval.label',
    descriptionKey: 'settings.advanced.updateCheckInterval.description',
    keywords: ['update', 'interval', 'background', 'check'],
    type: 'duration',
    default: 3600000, // 60 minutes
    component: 'duration',
    constraints: {
      unit: 'min',
      minMs: 300000, // 5 min
      maxMs: 86400000, // 24 hours
    },
  },
]
