// MTP (Android device) support (macOS and Linux)

import { type UnlistenFn } from '@tauri-apps/api/event'
import {
  commands,
  events,
  type DestinationRootEcho,
  type Initiator,
  type MtpDeviceConnected,
  type MtpDeviceDisconnected,
  type MtpExclusiveAccessError,
  type MtpPermissionError,
  type MtpStorageInfo as MtpStorageInfoBinding,
  type SpaceShortfall,
  type WriteAccess,
} from '$lib/ipc/bindings'
import type { ConflictResolution, WriteOperationStartResult } from '../file-explorer/types'
import { throwIpcError } from './ipc-types'

/**
 * Enables or disables MTP (Android device) support at runtime.
 * When disabled, stops USB device detection and disconnects all MTP devices.
 */
export async function setMtpEnabled(enabled: boolean): Promise<void> {
  await commands.setMtpEnabled(enabled)
}

/** Information about a connected MTP device. */
export interface MtpDeviceInfo {
  /** Unique identifier for the device (format: "mtp-{locationId}"). */
  id: string
  /** Physical USB location identifier. Stable for a given port. */
  locationId: number
  /** USB vendor ID (for example, 0x18d1 for Google). */
  vendorId: number
  /** USB product ID. */
  productId: number
  /** Device manufacturer name, if available. */
  manufacturer?: string
  /** Device product name, if available. */
  product?: string
  /** USB serial number, if available. */
  serialNumber?: string
}

/**
 * Information about a storage area on an MTP device.
 * Aliased to the `tauri-specta`-generated type so it matches the
 * `mtp-device-connected` event payload's nested storages exactly.
 */
export type MtpStorageInfo = MtpStorageInfoBinding

/** Information about a connected MTP device including its storages. */
export interface ConnectedMtpDeviceInfo {
  /** Device information. */
  device: MtpDeviceInfo
  /** Available storages on the device. */
  storages: MtpStorageInfo[]
}

/** Error types for MTP connection operations. */
export type MtpConnectionError =
  | { type: 'deviceNotFound'; deviceId: string }
  | { type: 'notConnected'; deviceId: string }
  | { type: 'exclusiveAccess'; deviceId: string; blockingProcess?: string }
  | { type: 'permissionDenied'; deviceId: string }
  | { type: 'timeout'; deviceId: string }
  | { type: 'disconnected'; deviceId: string }
  | { type: 'protocol'; deviceId: string; message: string }
  | { type: 'other'; deviceId: string; message: string }
  | { type: 'notSupported'; message: string }

/**
 * Connects to an MTP device by ID.
 * Opens an MTP session and retrieves storage information.
 * If another process has exclusive access, an 'mtp-exclusive-access-error' event is emitted.
 * @param deviceId - The device ID (`mtp-{locationId}`)
 * @returns Information about the connected device including storages
 */
export async function connectMtpDevice(deviceId: string): Promise<ConnectedMtpDeviceInfo> {
  const res = await commands.connectMtpDevice(deviceId)
  if (res.status === 'error') {
    // The error is a tagged-union MtpConnectionError, not an Error object; callers read its
    // `type`. Lint can't see that pattern.
    // eslint-disable-next-line @typescript-eslint/only-throw-error -- tagged-union MtpConnectionError, discriminated on `type` by the caller
    throw res.error
  }
  return res.data as ConnectedMtpDeviceInfo
}

/**
 * Gets the ptpcamerad workaround command for macOS.
 * Returns the Terminal command users can run to work around ptpcamerad blocking MTP.
 */
export async function getPtpcameradWorkaroundCommand(): Promise<string> {
  try {
    return await commands.getPtpcameradWorkaroundCommand()
  } catch {
    return ''
  }
}

// The event payload types are generated by `tauri-specta` into `bindings.ts`. We re-export them
// under their historical `*Event` names so consumers keep a stable import surface.
export type MtpExclusiveAccessErrorEvent = MtpExclusiveAccessError
export type MtpPermissionErrorEvent = MtpPermissionError
export type MtpDeviceConnectedEvent = MtpDeviceConnected
export type MtpDeviceDisconnectedEvent = MtpDeviceDisconnected

/**
 * Subscribes to MTP exclusive access error events.
 * Emitted when connecting fails because another process (like ptpcamerad) has the device.
 */
export async function onMtpExclusiveAccessError(
  callback: (event: MtpExclusiveAccessErrorEvent) => void,
): Promise<UnlistenFn> {
  return events.mtpExclusiveAccessError.listen((event) => {
    callback(event.payload)
  })
}

/**
 * Subscribes to MTP permission error events (Linux only).
 * Emitted when USB device access fails due to missing udev rules.
 */
export async function onMtpPermissionError(callback: (event: MtpPermissionErrorEvent) => void): Promise<UnlistenFn> {
  return events.mtpPermissionError.listen((event) => {
    callback(event.payload)
  })
}

/**
 * Subscribes to MTP device connected events.
 */
export async function onMtpDeviceConnected(callback: (event: MtpDeviceConnectedEvent) => void): Promise<UnlistenFn> {
  return events.mtpDeviceConnected.listen((event) => {
    callback(event.payload)
  })
}

/**
 * Subscribes to MTP device disconnected events.
 */
export async function onMtpDeviceDisconnected(
  callback: (event: MtpDeviceDisconnectedEvent) => void,
): Promise<UnlistenFn> {
  return events.mtpDeviceDisconnected.listen((event) => {
    callback(event.payload)
  })
}

// ============================================================================
// Unified volume copy operations
// ============================================================================

/** Conflict information for a file that already exists at destination. */
export interface VolumeConflictInfo {
  sourcePath: string
  destPath: string
  sourceSize: number
  destSize: number
  sourceModified: number | null
  destModified: number | null
  /** `true` when the source item is a directory. Lets the FE classify a
   *  dir-vs-dir collision as a silent merge ("will merge") instead of a
   *  conflict. */
  sourceIsDirectory: boolean
  /** `true` when the destination item is a directory. See `sourceIsDirectory`. */
  destIsDirectory: boolean
}

/** Configuration for volume copy operations. */
export interface VolumeCopyConfig {
  progressIntervalMs: number
  conflictResolution: ConflictResolution
  maxConflictsToShow: number
  /** Preview scan ID to reuse cached scan results (from startScanPreview). */
  previewId?: string | null
  /**
   * Source filenames already known to conflict at the destination (from the
   * pre-flight `scanVolumeForConflicts` call). When `conflictResolution` is
   * `'skip'`, the backend bulk-skips these upfront so the progress bar
   * reflects them immediately instead of advancing one-per-conflict as the
   * loop re-discovers them. Ignored for other resolution modes.
   */
  preKnownConflicts?: string[]
  /** Explicit leaf name for a single local copy. */
  destinationName?: string
  /**
   * Deflate compression level (1..=9) for zip writes the operation performs
   * (Compress, and copy/move INTO an archive). `null`/omitted uses the zip
   * crate default (level 6). The backend clamps out-of-range values and ignores
   * it for non-archive copies. See `behavior.archiveCompressionLevel`.
   */
  compressionLevel?: number | null
  /** What the copy does when the destination looks too small (`"proceed"` after "Copy anyway"). */
  spaceShortfall?: SpaceShortfall
}

/** Input for source item in conflict scanning. */
export interface SourceItemInput {
  name: string
  isDirectory?: boolean
  size: number
  modified: number | null
}

/**
 * Copies files between any two volumes (local, MTP, etc.).
 * This is the unified copy command that works for all volume types:
 * - Local -> Local (regular file copy)
 * - Local -> MTP (upload to Android device)
 * - MTP -> Local (download from Android device)
 *
 * @param sourceVolumeId - ID of the source volume (like "root" for local filesystem)
 * @param sourcePaths - List of source file/directory paths relative to source volume
 * @param destVolumeId - ID of the destination volume
 * @param destPath - Destination directory path relative to destination volume
 * @param config - Optional copy configuration
 * @returns Operation start result with operation ID
 */
export async function copyBetweenVolumes(
  sourceVolumeId: string,
  sourcePaths: string[],
  destVolumeId: string,
  destPath: string,
  config?: VolumeCopyConfig,
  initiator?: Initiator,
): Promise<WriteOperationStartResult> {
  const res = await commands.copyBetweenVolumes(
    sourceVolumeId,
    sourcePaths,
    destVolumeId,
    destPath,
    config ?? null,
    initiator ?? null,
  )
  if (res.status === 'error') throwIpcError(res.error)
  return res.data
}

/**
 * Moves files between any two volumes (local, MTP, etc.).
 * The backend picks the best strategy:
 * - Same volume: native rename/move (instant for MTP MoveObject)
 * - Both local: native move (rename for same-fs, copy+delete for cross-fs)
 * - Cross-volume: copy to destination, then delete source
 */
export async function moveBetweenVolumes(
  sourceVolumeId: string,
  sourcePaths: string[],
  destVolumeId: string,
  destPath: string,
  config?: VolumeCopyConfig,
  initiator?: Initiator,
): Promise<WriteOperationStartResult> {
  const res = await commands.moveBetweenVolumes(
    sourceVolumeId,
    sourcePaths,
    destVolumeId,
    destPath,
    config ?? null,
    initiator ?? null,
  )
  if (res.status === 'error') throwIpcError(res.error)
  return res.data
}

/**
 * A rename that runs as a move on one volume: `sourcePath` moves into the folder
 * `destPath` under `newName`. What the Move dialog confirms when F2 opens it for
 * a rename that copies (a big S3 folder, `RenameValidityResult.byMove`). Same
 * events as `moveBetweenVolumes`.
 */
export async function renameByMove(
  volumeId: string,
  sourcePath: string,
  destPath: string,
  newName: string,
  config?: VolumeCopyConfig,
  initiator?: Initiator,
): Promise<WriteOperationStartResult> {
  const res = await commands.renameByMove(volumeId, sourcePath, destPath, newName, config ?? null, initiator ?? null)
  if (res.status === 'error') throwIpcError(res.error)
  return res.data
}

/**
 * Compresses files into a NEW zip at `destZipPath` on `destVolumeId`, reusing the
 * archive-edit machinery (seed a valid empty zip, then pack the sources in). Same
 * events as `copyBetweenVolumes`. The destination may be local or remote (SMB/MTP):
 * a local target is seeded on the filesystem, a remote one through the parent volume.
 *
 * @param sourceVolumeId - ID of the source volume (like "root" for local filesystem)
 * @param sourcePaths - Source file/directory paths relative to the source volume
 * @param destVolumeId - ID of the destination (parent) volume holding the new zip
 * @param destZipPath - Full path of the new `.zip` on the destination volume
 * @param config - Optional copy configuration
 * @returns Operation start result with operation ID
 */
export async function compressFiles(
  sourceVolumeId: string,
  sourcePaths: string[],
  destVolumeId: string,
  destZipPath: string,
  config?: VolumeCopyConfig,
  initiator?: Initiator,
): Promise<WriteOperationStartResult> {
  const res = await commands.compressFiles(
    sourceVolumeId,
    sourcePaths,
    destVolumeId,
    destZipPath,
    config ?? null,
    initiator ?? null,
  )
  if (res.status === 'error') throwIpcError(res.error)
  return res.data
}

/**
 * Whether the destination folder takes writes, for the transfer dialog's notice
 * under its path box. `unknown` when the volume can't tell, isn't connected, or
 * didn't answer in time, which shows nothing: the transfer asks again before it
 * writes, and that answer is the one that refuses.
 */
export async function destinationWriteAccess(destVolumeId: string, destPath: string): Promise<WriteAccess> {
  return commands.destinationWriteAccess(destVolumeId, destPath)
}

/**
 * Both readings of a destination that starts with the place's own root folder
 * (`/srv/data/photos` on a place rooted at `/srv/data`), for the transfer
 * dialog's warning, or `null` when the path reads only one way. Never rewrites
 * anything: the transfer goes where the box says.
 */
export async function destinationRootEcho(destVolumeId: string, destPath: string): Promise<DestinationRootEcho | null> {
  return commands.destinationRootEcho(destVolumeId, destPath)
}

/**
 * Scans destination volume for conflicts with source items.
 * Checks if any of the source item names already exist at the destination path.
 *
 * When `sourceVolumeId` and `sourcePaths` are both provided, the backend
 * resolves each item's real `is_directory` and size authoritatively from the
 * source volume (one batched stat, never a subtree walk), so the FE can
 * classify dir-vs-dir collisions as silent merges. Omit them for the legacy
 * name-only check.
 *
 * @param volumeId - ID of the destination volume to scan
 * @param sourceItems - List of source items to check
 * @param destPath - Destination directory path on the volume
 * @param sourceVolumeId - ID of the source volume, for authoritative type/size resolution
 * @param sourcePaths - Source paths on `sourceVolumeId`, aligned with `sourceItems` by name
 * @returns List of conflicts found
 */
export async function scanVolumeForConflicts(
  volumeId: string,
  sourceItems: SourceItemInput[],
  destPath: string,
  sourceVolumeId?: string,
  sourcePaths?: string[],
): Promise<VolumeConflictInfo[]> {
  const res = await commands.scanVolumeForConflicts(
    volumeId,
    sourceItems,
    destPath,
    sourceVolumeId ?? null,
    sourcePaths ?? null,
  )
  if (res.status === 'error') throwIpcError(res.error)
  return res.data
}
