/**
 * ESLint configuration for the analytics dashboard.
 *
 * Mirrors the api-server's strict TypeScript setup, plus the Svelte blocks the desktop app uses.
 * Formatting is oxfmt's job monorepo-wide; `eslint-config-prettier` switches off the rules that
 * would fight it.
 *
 * Type-aware rules need `.svelte-kit/tsconfig.json` (generated by `svelte-kit sync`), which
 * `tsconfig.json` extends. The `dashboard-eslint` check refuses to run when it's missing rather
 * than let type-aware rules silently pass, which `--fix` would then "clean up" into deleted
 * eslint-disable comments.
 */
import js from '@eslint/js'
import prettierConfig from 'eslint-config-prettier'
import tseslint from 'typescript-eslint'
import svelte from 'eslint-plugin-svelte'
import svelteParser from 'svelte-eslint-parser'
import betterTailwindcss from 'eslint-plugin-better-tailwindcss'
import globals from 'globals'
import noErrorStringMatch from '../../eslint-plugins/no-error-string-match.js'
import noConfusableCallbackParams from '../../eslint-plugins/no-confusable-callback-params.js'
import noIsolatedTests from '../../eslint-plugins/no-isolated-tests.js'

// Underscore-prefixed names are an intentional "deliberately unused" marker, same as desktop.
const unusedVarsRule = ['error', { argsIgnorePattern: '^_', varsIgnorePattern: '^_', caughtErrorsIgnorePattern: '^_' }]

const projectServiceConfig = { projectService: true, tsconfigRootDir: import.meta.dirname }

export default tseslint.config(
  {
    ignores: ['.svelte-kit', 'build', '.wrangler', 'node_modules'],
  },
  js.configs.recommended,
  prettierConfig,
  ...svelte.configs['flat/recommended'],
  ...tseslint.configs.strictTypeChecked.map((config) => ({
    ...config,
    files: ['**/*.{ts,svelte}'],
  })),
  {
    files: ['**/*.ts'],
    plugins: {
      '@typescript-eslint': tseslint.plugin,
    },
    languageOptions: {
      parser: tseslint.parser,
      ecmaVersion: 'latest',
      sourceType: 'module',
      globals: { ...globals.browser, ...globals.node, ...globals.es2021 },
      parserOptions: projectServiceConfig,
    },
    rules: {
      // The base rule false-positives on function-type params when run on a TS AST.
      'no-unused-vars': 'off',
      '@typescript-eslint/no-unused-vars': unusedVarsRule,
      '@typescript-eslint/no-unsafe-assignment': 'error',
      '@typescript-eslint/no-unsafe-call': 'error',
      '@typescript-eslint/no-unsafe-member-access': 'error',
      '@typescript-eslint/no-unsafe-return': 'error',
      '@typescript-eslint/no-floating-promises': 'error',
      '@typescript-eslint/await-thenable': 'error',
      '@typescript-eslint/no-misused-promises': 'error',
      '@typescript-eslint/require-await': 'error',
      '@typescript-eslint/no-explicit-any': 'error',
      // Server code logs to the Workers console; that's the dashboard's only diagnostic channel.
      'no-console': 'off',
      complexity: ['error', { max: 15 }],
    },
  },
  {
    files: ['**/*.svelte'],
    languageOptions: {
      parser: svelteParser,
      parserOptions: {
        parser: tseslint.parser,
        ...projectServiceConfig,
        extraFileExtensions: ['.svelte'],
      },
      globals: { ...globals.browser, ...globals.es2021 },
    },
    rules: {
      '@typescript-eslint/no-unused-vars': unusedVarsRule,
      'no-console': 'warn',
      complexity: ['error', { max: 15 }],
    },
  },
  {
    // Tailwind class hygiene, the same rule set as the website (`apps/website/eslint.config.js` explains
    // each choice).
    files: ['src/**/*.{ts,svelte}'],
    plugins: { 'better-tailwindcss': betterTailwindcss },
    settings: { 'better-tailwindcss': { entryPoint: 'src/app.css' } },
    rules: {
      'better-tailwindcss/enforce-canonical-classes': 'error',
      'better-tailwindcss/enforce-consistent-class-order': 'error',
      'better-tailwindcss/no-conflicting-classes': 'error',
      'better-tailwindcss/no-deprecated-classes': 'error',
      'better-tailwindcss/no-duplicate-classes': 'error',
      'better-tailwindcss/no-unnecessary-whitespace': 'error',
    },
  },
  {
    // Shared with the desktop app, which registers the same rules under the same names.
    files: ['src/**/*.{ts,svelte}'],
    plugins: {
      cmdr: {
        rules: {
          'no-error-string-match': noErrorStringMatch,
          'no-confusable-callback-params': noConfusableCallbackParams,
        },
      },
    },
    rules: { 'cmdr/no-error-string-match': 'error', 'cmdr/no-confusable-callback-params': 'error' },
  },
  {
    files: ['src/**/*.test.ts'],
    plugins: { custom: { rules: { 'no-isolated-tests': noIsolatedTests } } },
    rules: {
      'custom/no-isolated-tests': 'error',
      // Test fixtures delete dynamic keys off mock objects, which runtime code shouldn't.
      '@typescript-eslint/no-dynamic-delete': 'off',
      '@typescript-eslint/no-unsafe-assignment': 'off',
      '@typescript-eslint/no-unsafe-member-access': 'off',
    },
  },
  {
    // Config files run under Node and sit outside the generated `.svelte-kit/tsconfig.json`
    // include list, so the project service can't type them. Lint them without type-aware rules
    // rather than adding them to the TS project just to satisfy the linter.
    files: ['svelte.config.js', 'vite.config.ts', 'vitest.config.ts'],
    extends: [tseslint.configs.disableTypeChecked],
    languageOptions: {
      ecmaVersion: 'latest',
      sourceType: 'module',
      globals: { ...globals.node },
    },
  },
)
